const creators={ccbcm:{name:'CCBCM',letter:'C',note:'我的创作角落。先从一座可以走进去的城市开始。',kind:'站内创作者'},vanta:{name:'Teng Bao',letter:'T',note:'Vanta 动态背景的作者。这里收录的是开源作品，并非作者入驻。',kind:'开源作者',url:'https://github.com/tengbao/vanta'},daylin:{name:'Daylin Morgan',letter:'D',note:'用代码和柔和配色做壁纸。这里收录的是开源作品，并非作者入驻。',kind:'开源作者',url:'https://github.com/daylinmorgan/catppuccin-wallpapers'}};
const works=[
{id:'waves',name:'海面慢慢',author:'vanta',type:'动态壁纸',tag:'自然',cover:'waves.jpg',text:'不用去很远，也可以看一会儿海。缓缓起伏的波纹，跟随鼠标轻轻改变视角。',original:'Waves',source:'https://github.com/tengbao/vanta',license:'MIT'},
{id:'clouds',name:'云上散步',author:'vanta',type:'动态壁纸',tag:'自然',cover:'clouds.jpg',text:'把天空留在桌面上。云层缓慢向前，适合安静地陪你工作。',original:'Clouds',source:'https://github.com/tengbao/vanta',license:'MIT'},
{id:'net',name:'星点之间',author:'vanta',type:'动态壁纸',tag:'抽象',cover:'net.jpg',text:'点与线在深色背景中舒展。移动鼠标，可以和这片小小的星网互动。',original:'Net',source:'https://github.com/tengbao/vanta',license:'MIT'},
{id:'cat',name:'一只小猫',author:'daylin',type:'静态壁纸',tag:'极简',cover:'cat.svg',text:'一点柔和的颜色，和一只不打扰你的小猫。保留原作者的 SVG 壁纸，可直接下载。',original:'Cat',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'},
{id:'city',name:'陆家嘴 · 城市漫游',author:'ccbcm',type:'互动作品',tag:'城市',cover:'city.png',text:'从江面看看东方明珠和三座高楼，也可以走进街区。场景还在慢慢完善，先把这一段创作留在这里。',original:'制作中',source:'https://github.com/ccbcm/The-world',license:'各素材许可见工程说明'},
{id:'lines',name:'线条的秩序',author:'daylin',type:'静态壁纸',tag:'极简',cover:'lines.svg',text:'干净的线条，让桌面留一点空。来自 Catppuccin Wallpapers 的原始矢量作品。',original:'Lines',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'},
{id:'caffeine',name:'咖啡时间',author:'daylin',type:'静态壁纸',tag:'极简',cover:'caffeine.svg',text:'给工作间隙留一杯咖啡。简洁的分子图案，适合喜欢安静桌面的你。',original:'Caffeine',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'},
{id:'tux',name:'企鹅朋友',author:'daylin',type:'静态壁纸',tag:'极简',cover:'tux.svg',text:'熟悉的小企鹅，换上柔和的底色。来自原作者的开源壁纸系列。',original:'Tux',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'}];
const app=document.querySelector('#app'),dialog=document.querySelector('#detail');let saved=new Set();try{saved=new Set(JSON.parse(localStorage.getItem('ccbcm-saved')||'[]'))}catch{}let filter='全部',query='',route='discover',toastTimer;
const image=w=>'/gallery/media/'+w.cover;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){let el=document.querySelector('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function heart(w){return `<button class="heart ${saved.has(w.id)?'selected':''}" data-save="${w.id}" aria-label="${saved.has(w.id)?'取消收藏':'收藏'} ${w.name}" aria-pressed="${saved.has(w.id)}">${saved.has(w.id)?'♥':'♡'}</button>`}
function card(w){return `<article class="card"><button class="cover" data-work="${w.id}" aria-label="查看 ${w.name}"><img src="${image(w)}" alt="${w.name}" loading="lazy" width="600" height="375"><span class="badge">${w.type==='动态壁纸'?'▷ ':w.type==='互动作品'?'◈ ':''}${w.type}</span></button><div class="card-info"><div><h3>${w.name}</h3><a class="author" href="#creator/${w.author}">${creators[w.author].name} ${w.author==='ccbcm'?'':'· 开源精选'}</a></div>${heart(w)}</div></article>`}
function toolbar(title,sub){return `<section class="intro-line"><div><h2>${title}</h2><div class="subtitle">${sub}</div></div><label class="search"><span aria-hidden="true">⌕</span><input id="search" aria-label="搜索作品" placeholder="搜壁纸、风格或作者" value="${escape(query)}" type="search"></label></section><div class="filters" role="group" aria-label="作品分类">${['全部','动态壁纸','静态壁纸','互动作品','极简','自然'].map(f=>`<button class="chip ${filter===f?'active':''}" data-filter="${f}" aria-pressed="${filter===f}">${f}</button>`).join('')}</div><section class="grid" id="grid" aria-label="作品"></section>`}
function renderGrid(){let list=works.filter(w=>(route!=='wallpapers'||w.type!=='互动作品')&&(route!=='saved'||saved.has(w.id))&&(!route.startsWith('creator/')||w.author===route.split('/')[1])&&(filter==='全部'||w.type===filter||w.tag===filter)&&(`${w.name} ${creators[w.author].name} ${w.tag} ${w.original}`).toLowerCase().includes(query.toLowerCase()));document.querySelector('#grid').innerHTML=list.length?list.map(card).join(''):`<div class="empty">${route==='saved'?'还没有收藏。遇到喜欢的作品，点一下 ♡ 就能留在这里。':'没有找到合适的作品，换个词试试。'}</div>`}
function render(){route=location.hash.slice(1)||'discover';filter='全部';query='';if(dialog.open)dialog.close();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route||route.startsWith('creator/')&&a.dataset.nav==='creators'));
if(route==='creators'){app.innerHTML=`<section class="intro-line"><div><p class="eyebrow">PEOPLE & IDEAS</p><h1>看看谁在创作</h1><p class="subtitle">从一件喜欢的作品，认识它背后的人。</p></div></section><section class="creators-grid">${Object.entries(creators).map(([id,c])=>`<article class="creator-card"><span class="avatar">${c.letter}</span><h2>${c.name}</h2><span class="subtitle">${c.kind}</span><p>${c.note}</p><a class="pill secondary" href="#creator/${id}">看看作品 ↗</a></article>`).join('')}</section>`;return}
if(route.startsWith('creator/')){let c=creators[route.split('/')[1]];if(!c){app.innerHTML='<div class="empty">这个主页还不存在。<a href="#creators">返回创作者</a></div>';return}app.innerHTML=`<section class="profile"><span class="avatar">${c.letter}</span><div><p class="eyebrow">${c.kind}</p><h1>${c.name}</h1><p>${c.note}</p>${c.url?`<a class="author" href="${c.url}" target="_blank" rel="noopener">GitHub ↗</a>`:''}</div></section>`+toolbar('作品','壁纸之外，也留一些别的灵感。');}
else{const isHome=route==='discover';app.innerHTML=(isHome?`<section class="hero"><div class="hero-copy"><p class="eyebrow">A LITTLE ESCAPE</p><h1>换个喜欢的风景。</h1><p>让桌面安静一点，也生动一点。<br>挑一张壁纸，看看创作者的世界。</p><a href="#wallpapers" class="pill">去逛逛 <span>↗</span></a></div><button class="hero-art" data-work="waves" aria-label="查看海面慢慢"><img src="/gallery/media/waves.jpg" alt="青蓝色起伏的海面" width="1400" height="850" fetchpriority="high"><div class="hero-label"><div><strong>海面慢慢</strong><small>Vanta · 动态壁纸</small></div><span class="play-circle">▷</span></div></button></section>`:'')+toolbar(route==='saved'?'留住喜欢的':route==='wallpapers'?'挑一张，陪你工作':'值得停留的风景',route==='saved'?'收藏保存在这台设备的浏览器里。':'先看封面，喜欢再点开。')+(isHome?`<section class="collection"><span class="orb">◈</span><div><h2>不止壁纸，还有一个小世界</h2><p>CCBCM 的陆家嘴，正在一点点长出来。</p></div><a class="pill secondary" href="#creator/ccbcm">去我的创作角落 ↗</a></section>`:'');}
renderGrid();document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;renderGrid()});}
function openWork(id){let w=works.find(w=>w.id===id);if(!w)return;let dynamic=w.type==='动态壁纸';document.querySelector('#detail-body').innerHTML=`<div class="detail-cover"><img src="${image(w)}" alt="${w.name}">${dynamic?'<button class="pill start" id="start">▷ 播放预览</button>':''}</div><div class="detail-copy"><p class="eyebrow">${w.type} · ${w.tag}</p><h2>${w.name}</h2><a class="author" href="#creator/${w.author}">${creators[w.author].name} ↗</a><p>${w.text}</p><div class="detail-actions">${w.id==='city'?'<a class="pill" href="/city.html">进入城市 ↗</a>':dynamic?`<a class="pill secondary" href="/gallery/preview.html?id=${w.id}" target="_blank" rel="noopener">单独打开 ↗</a>`:`<a class="pill" href="${image(w)}" download="${w.id}.svg">下载壁纸 ↓</a>`}<a class="pill secondary" href="${w.source}" target="_blank" rel="noopener">${dynamic?'获取源码 ↗':'查看来源 ↗'}</a>${heart(w)}</div><div class="meta"><span>${w.original}</span><span>${w.license}</span><span>${dynamic?'网页动态效果':w.id==='city'?'制作中 · 电脑体验更好':'SVG · 可缩放'}</span></div>${dynamic?'<p class="subtitle">这是网页动态效果，不是视频文件。用作桌面壁纸时，需要支持网页壁纸的软件。关闭预览后会停止运行。</p>':''}</div>`;dialog.showModal();document.querySelector('#start')?.addEventListener('click',()=>{document.querySelector('.detail-cover').innerHTML=`<iframe src="/gallery/preview.html?id=${id}" title="${w.name} 动态预览" sandbox="allow-scripts allow-same-origin"></iframe>`});}
document.addEventListener('click',e=>{let work=e.target.closest('[data-work]');if(work)openWork(work.dataset.work);let b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderGrid()}let save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);try{localStorage.setItem('ccbcm-saved',JSON.stringify([...saved]));toast(saved.has(id)?'已加入收藏':'已取消收藏')}catch{toast('浏览器无法保存，收藏仅在本次访问有效')}document.querySelectorAll(`[data-save="${id}"]`).forEach(el=>{el.outerHTML=heart(works.find(w=>w.id===id))});if(route==='saved')renderGrid()}});
dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>document.querySelector('#detail-body').replaceChildren());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});document.querySelector('#about').onclick=()=>{document.querySelector('#detail-body').innerHTML='<div class="detail-copy"><p class="eyebrow">HELLO, CCBCM</p><h2>先放一些喜欢的作品。</h2><p>这里刚刚开始。现在可以浏览壁纸、播放预览、收藏作品，也可以看看 CCBCM 的三维城市。</p><p>开源精选保留原作者和来源，并非作者本人投稿。创作者注册、上传与发布功能还在准备中。</p><p>所有壁纸都需要主动点击才会播放。希望这里轻一点，也舒服一点。</p></div>';dialog.showModal()};render();
