let libraryItems=[],accountEpoch=0,libraryGeneration=0,favoriteRevision=0;const favoriteJobs=new Map();
import {discoveryOrder,startHero} from './discovery.js?v=discovery-1';
import {extractCover,mobileDevice,mobileLayout,portraitWork,mobileUse} from './media-tools.js?v=media-4';
let discoveryRanking=[],stopHero=()=>{};
matchMedia('(max-width:700px)').addEventListener('change',()=>{if(route==='downloads'){paintLibrary();return;}if(route!=='discover'||!document.querySelector('#grid'))return;renderGrid();stopHero();stopHero=startHero(document.querySelector('.hero-art'),works.filter(w=>mobileLayout()?portraitWork(w):!portraitWork(w)),discoveryRanking,{image,escape});});
const creators={ccbcm:{name:'CCBCM',letter:'C',note:'我的壁纸与创作，也整理一些注明来源的开源壁纸。',kind:'站内创作者'}};
const works=[
{id:"blue",name:"蓝色呼吸",author:"ccbcm",type:"动态壁纸",tag:"极简",cover:"blue.jpg",video:"/gallery/media/blue.mp4",text:"柔和的蓝色渐变，缓缓流动。下载后可在 CCBCM 插件中使用。",original:"CCBCM",source:"https://github.com/ccbcm/The-world",license:"CCBCM 原创演示"},
{id:'cat',name:'一只小猫',author:'ccbcm',sourceAuthor:'Daylin Morgan',type:'静态壁纸',tag:'极简',cover:'cat.svg',text:'一点柔和的颜色，和一只不打扰你的小猫。保留原作者的 SVG 壁纸，可直接下载。',original:'Cat',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'},
{id:'lines',name:'线条的秩序',author:'ccbcm',sourceAuthor:'Daylin Morgan',type:'静态壁纸',tag:'极简',cover:'lines.svg',text:'干净的线条，让桌面留一点空。来自 Catppuccin Wallpapers 的原始矢量作品。',original:'Lines',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'},
{id:'caffeine',name:'咖啡时间',author:'ccbcm',sourceAuthor:'Daylin Morgan',type:'静态壁纸',tag:'极简',cover:'caffeine.svg',text:'给工作间隙留一杯咖啡。简洁的分子图案，适合喜欢安静桌面的你。',original:'Caffeine',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'},
{id:'tux',name:'企鹅朋友',author:'ccbcm',sourceAuthor:'Daylin Morgan',type:'静态壁纸',tag:'极简',cover:'tux.svg',text:'熟悉的小企鹅，换上柔和的底色。来自原作者的开源壁纸系列。',original:'Tux',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'}];
const app=document.querySelector('#app'),dialog=document.querySelector('#detail');let saved=new Set();let filter='全部',query='',route='discover',toastTimer;
const image=w=>w.poster||'/gallery/media/'+w.cover;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){let el=document.querySelector('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function heart(w){return `<button class="heart ${saved.has(w.id)?'selected':''}" ${favoriteJobs.has(w.id)?'disabled aria-busy="true"':''} data-save="${w.id}" aria-label="${saved.has(w.id)?'取消收藏':'收藏'} ${escape(w.name)}" aria-pressed="${saved.has(w.id)}">${saved.has(w.id)?'♥':'♡'}</button>`}
function card(w){const author=w.ownerLogin||(creators[w.author]?.name||'作者')+(w.author==='ccbcm'?'':' · 开源精选'),href=w.uploaded?'#people/'+encodeURIComponent(w.ownerLogin):'#creator/'+w.author;return `<article class="card catalog-card"><button class="cover" data-work="${w.id}" aria-label="查看 ${escape(w.name)}"><img src="${image(w)}" alt="${escape(w.name)}" loading="lazy" width="600" height="375"><span class="badge">${escape(w.type)}</span></button><div class="card-info"><div class="card-text"><h3 title="${escape(w.name)}">${escape(w.name)}</h3><a class="author" title="${escape(author)}" href="${href}">${escape(author)}</a></div>${heart(w)}</div></article>`}
function toolbar(title,sub){return `<section class="intro-line"><div><h2>${title}</h2><div class="subtitle">${sub}</div></div><label class="search"><span aria-hidden="true">⌕</span><input id="search" aria-label="搜索作品" placeholder="搜壁纸、风格或作者" value="${escape(query)}" type="search"></label></section><div class="filters" role="group" aria-label="作品分类">${['全部','动态壁纸','静态壁纸','极简','自然'].map(f=>`<button class="chip ${filter===f?'active':''}" data-filter="${f}" aria-pressed="${filter===f}">${f}</button>`).join('')}</div><section class="grid" id="grid" aria-label="作品"></section>`}
function renderGrid(){let list=works.filter(w=>(route!=='discover'||(mobileLayout()?portraitWork(w):!portraitWork(w)))&&(route!=='wallpapers'||w.type!=='互动作品')&&(route!=='saved'||saved.has(w.id))&&(!route.startsWith('creator/')||w.author===route.split('/')[1])&&(filter==='全部'||w.type===filter||w.tag===filter)&&(`${w.name} ${w.ownerLogin||creators[w.author]?.name||''} ${w.tag} ${w.original}`).toLowerCase().includes(query.toLowerCase()));if(route==='discover')list=discoveryOrder(list,discoveryRanking);document.querySelector('#grid').innerHTML=list.length?list.map(card).join(''):`<div class="empty">${route==='saved'?'还没有收藏。遇到喜欢的作品，点一下 ♡ 就能留在这里。':'没有找到合适的作品，换个词试试。'}</div>`}
function render(){stopHero();stopHero=()=>{};route=location.hash.slice(1)||'discover';if(route==='wallpapers'){location.hash='discover';return;}filter='全部';query='';if(dialog.open)dialog.close();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route||route.startsWith('creator/')&&a.dataset.nav==='creators'));
document.querySelector('.account-menu').open=false;
if(route==='creator-review'){renderCreatorReview();return;}
if(route==='reports'){renderReports();return;}
if(route==='moderation'){renderModeration();return;}
if(route==='plugin'){app.innerHTML='<section class="intro-line"><div><h1>CCBCM 插件</h1><p class="subtitle">为电脑和手机准备的轻量工具，选好设备，直接使用。</p></div></section>'+'<div class="plugin-platforms">'+document.querySelector('#plugin-page').innerHTML+'</div>';return;}
if(['studio','me','settings'].includes(route)){renderPersonal(route);return;}
if(route==='saved'){history.replaceState(null,'','#downloads');route='downloads';}if(route.startsWith('people/')){renderPublic(route.slice(7));return;}if(!['discover','wallpapers','creators','downloads','saved'].includes(route)&&!route.startsWith('creator/')){app.innerHTML='<div class="empty"><h1>没有找到这个页面</h1><p>你可以回到发现，或从个人菜单进入自己的空间。</p><a class="pill" href="#discover">返回发现</a></div>';return;}
if(route==='downloads'){renderDownloads();return}
if(route==='creators'){renderCreators();return;}
if(route.startsWith('creator/')){renderPublic(route.slice(8));return;}
else{const isHome=route==='discover';app.innerHTML=(isHome?`<section class="hero"><div class="hero-copy"><p class="eyebrow">A LITTLE ESCAPE</p><h1>换个喜欢的风景。</h1><p>让桌面安静一点，也生动一点。<br>挑一张壁纸，看看创作者的世界。</p><a href="#discover" class="pill">去逛逛 <span>↗</span></a></div><div class="hero-art"><button class="hero-open" data-work="blue" aria-label="查看蓝色呼吸"><img src="/gallery/media/blue.jpg" alt="柔和的蓝色渐变" width="1400" height="850" fetchpriority="high"><div class="hero-label"><div><strong>蓝色呼吸</strong><small>CCBCM · 动态壁纸</small></div></div></button><div class="hero-controls" role="group" aria-label="背景轮播"><button type="button" data-hero-prev aria-label="上一张">‹</button><span class="hero-position">1 / 1</span><button type="button" data-hero-next aria-label="下一张">›</button></div></div></section>`:'')+toolbar(route==='saved'?'留住喜欢的':route==='wallpapers'?'挑一张，陪你工作':'值得停留的风景',route==='saved'?'收藏保存在这台设备的浏览器里。':'先看封面，喜欢再点开。')}
renderGrid();if(route==='discover')stopHero=startHero(document.querySelector('.hero-art'),works.filter(w=>mobileLayout()?portraitWork(w):!portraitWork(w)),discoveryRanking,{image,escape});document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;renderGrid()});}
function openWork(id){let w=works.find(w=>w.id===id);if(!w)return;recordClick(id);let dynamic=w.type==='动态壁纸';if(w.uploaded){openUploaded(w);return;}if(w.video){openVideo(w);return;}document.querySelector('#detail-body').innerHTML=`<div class="detail-cover"><img src="${image(w)}" alt="${w.name}">${dynamic?'<button class="pill start" id="start">▷ 播放预览</button>':''}</div><div class="detail-copy"><p class="eyebrow">${w.type} · ${w.tag}</p><h2>${w.name}</h2><a class="author" href="#creator/${w.author}">${creators[w.author].name} ↗</a><p>${w.text}</p><div class="detail-actions">${w.id==='city'?'<a class="pill" href="/city.html">进入城市 ↗</a>':`<button class="pill" data-download="${w.id}">下载</button>`}${heart(w)}</div><div class="meta"><span>${w.sourceAuthor?'CCBCM 整理 · 原作者 '+escape(w.sourceAuthor):w.original}</span><span>${w.license}</span><span>${dynamic?'网页动态效果':w.id==='city'?'制作中 · 电脑体验更好':'SVG · 可缩放'}</span></div>${dynamic?'<p class="subtitle">这是网页动态效果，不是视频文件。用作桌面壁纸时，需要支持网页壁纸的软件。关闭预览后会停止运行。</p>':''}</div>`;dialog.showModal();document.querySelector('#start')?.addEventListener('click',()=>{document.querySelector('.detail-cover').innerHTML=`<iframe src="/gallery/preview.html?id=${id}" title="${w.name} 动态预览" sandbox="allow-scripts allow-same-origin"></iframe>`});}
document.addEventListener('click',e=>{let work=e.target.closest('[data-work]');if(work)openWork(work.dataset.work);let b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderGrid()}let save=e.target.closest('[data-save]');if(save)toggleFavorite(save);});

dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>document.querySelector('#detail-body').replaceChildren());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});document.querySelector('#about').onclick=()=>{document.querySelector('#detail-body').innerHTML='<div class="detail-copy"><h2>让桌面有点不同。</h2><p>CCBCM 是一个分享壁纸与创作的地方。先看看预览，点亮爱心的壁纸会排在“我的下载”前面。下载后即可使用。</p><p>安装桌面插件后，在“我的下载”点击“使用”，插件会准备壁纸并应用到桌面。目前支持视频动态壁纸和站内静态壁纸。</p><p>GitHub 登录后即可收藏和使用壁纸。想分享自己的创作，可以申请成为创作者，由 CCBCM 审核；作品提交后也需审核再上架。</p><p>收藏和下载仅自己可见，公开主页展示已发布的作品。收录的开源壁纸会在详情中保留原作者与许可说明。</p></div>';dialog.showModal()};


let accountPromise;
async function api(path,options={}){
 if(['127.0.0.1','localhost'].includes(location.hostname))throw Error('这是本地页面预览，账号功能请到 ccbcm.net 使用。');
 const read=(options.method||'GET').toUpperCase()==='GET';
 for(let attempt=0;attempt<(read?2:1);attempt++){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);
  try{
   const r=await fetch('/api/'+path,{credentials:'same-origin',...options,signal:controller.signal});
   if(read&&attempt===0&&[502,503,504].includes(r.status)){await r.body?.cancel();continue;}
   let data;try{data=await r.json()}catch{throw Error('服务没有正确响应，请重试。')}
   if(!r.ok)throw Object.assign(Error(data.error||'暂时无法完成，请重试。'),{status:r.status});return data;
  }catch(error){if(read&&attempt===0&&(error.name==='AbortError'||error instanceof TypeError))continue;
   if(error.name==='AbortError'||error instanceof TypeError)throw Error('连接暂时中断，请点重试，无需关闭页面。');throw error;
  }finally{clearTimeout(timer)}
 }
}
function account(){return accountPromise||(accountPromise=api('account').catch(error=>{accountPromise=null;throw error}));}
function loginPanel(ready){return `<div class="empty account-panel"><h2>${ready?'把喜欢的壁纸留在这里':'我的下载即将开放'}</h2><p>${ready?'登录后，下载和收藏会保存在你的账号中。':'账号服务正在配置。'}</p>${ready?'<button class="pill" type="button" data-open-login>使用邮箱登录</button><dialog class="login-sheet" data-login-sheet aria-label="选择登录方式"><div class="login-sheet-card"><button class="login-close" type="button" data-close-login aria-label="关闭登录">×</button><h3>选择登录方式</h3><p class="subtitle">邮箱验证码支持 Gmail、QQ 和其他常见邮箱。</p><a class="pill secondary" href="/api/auth/github">使用 GitHub 账号继续</a><form class="email-login" id="email-login-form"><label>邮箱<input name="email" type="email" autocomplete="email" placeholder="输入你的邮箱地址" required></label><div class="email-code-row"><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="验证码"><button class="pill secondary" type="button" data-email-code>获取验证码</button></div><button class="pill" type="submit">继续</button><p role="status"></p></form></div></dialog>':''}</div>`;}
async function saveDownload(id){const w=works.find(w=>w.id===id);if(!w)return false;try{const a=await account();if(!a.user){try{sessionStorage.setItem('ccbcm-pending-download',JSON.stringify({id,at:Date.now(),returnTo:route}));}catch{}document.querySelector('#detail-body').innerHTML=loginPanel(a.ready);if(!dialog.open)dialog.showModal();return false;}await api('downloads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});toast('已加入我的下载');if(route==='downloads')await renderDownloads();return true;}catch(e){toast(e.message);if(e.status===401)accountPromise=null;return false;}}
function paintLibrary(){const grid=document.querySelector('#download-grid');if(!grid)return;
 const merged=new Map(libraryItems.map(x=>[x.id,{...x,favorite:saved.has(x.id)}]));for(const id of saved)if(!merged.has(id))merged.set(id,{id,downloaded:false,favorite:true,date:0});
 const items=[...merged.values()].filter(x=>(x.downloaded||x.favorite)&&!['city','waves','clouds','net'].includes(x.id)).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||b.date-a.date||a.id.localeCompare(b.id));
 grid.innerHTML=items.map(x=>downloadCard(works.find(w=>w.id===x.id),x.id,!!x.downloaded)).join('')||'<div class="empty">还没有留下壁纸。点亮爱心，或下载一张喜欢的风景。<br><a class="pill secondary" href="#discover">去找壁纸</a></div>';
}
async function renderDownloads(){const generation=++libraryGeneration;app.innerHTML='<section class="intro-line"><div><h1>我的下载</h1><p class="subtitle">喜欢的排在前面。下载后，点使用就能换到桌面。</p></div><a class="pill secondary" href="#discover">去找壁纸 ↗</a></section><p class="subtitle">首次使用？<a href="#plugin">安装桌面插件</a></p><div id="library-import"></div><section class="grid" id="download-grid"><p>正在读取…</p></section>';
 try{const a=await account();if(route!=='downloads'||generation!==libraryGeneration)return;if(!a.user){document.querySelector('#download-grid').innerHTML=loginPanel(a.ready);return;}
 const revision=favoriteRevision,{items}=await api('library');if(route!=='downloads'||generation!==libraryGeneration)return;libraryItems=items;
 if(revision===favoriteRevision)saved=new Set(items.filter(x=>x.favorite).map(x=>x.id));for(const [id,desired] of favoriteJobs)desired?saved.add(id):saved.delete(id);paintHearts();paintLibrary();
 const old=legacyFavorites();if(old.length)document.querySelector('#library-import').innerHTML=`<details class="legacy-drafts"><summary>导入这台浏览器的旧收藏</summary><p>确认这 ${old.length} 件是你的收藏，再导入账号 @${escape(a.user.login)}。</p><button class="pill secondary" data-import-favorites>导入到这个账号</button><p id="import-status" role="status"></p></details>`;
 }catch(e){if(route==='downloads'&&generation===libraryGeneration)document.querySelector('#download-grid').innerHTML=`<div class="empty">${escape(e.message)}<br><button class="pill secondary" data-retry>重试</button></div>`;}}

function openVideo(w){if(w.uploaded){openUploaded(w);return;}document.querySelector('#detail-body').innerHTML=`<div class="detail-cover"><video controls muted loop playsinline preload="none" poster="${image(w)}" src="${w.video}" style="width:100%;height:100%;object-fit:cover"></video></div><div class="detail-copy"><p class="eyebrow">动态壁纸 · 极简</p><h2>${w.name}</h2><p>${w.text}</p><div class="detail-actions"><button class="pill" data-download="${w.id}">下载</button>${heart(w)}</div></div>`;dialog.showModal();}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-download]');if(b){e.preventDefault();b.disabled=true;const label=b.textContent;b.textContent='保存中…';let done=false;try{done=await saveDownload(b.dataset.download)}finally{b.disabled=done;b.textContent=done?'已下载':label;}}if(e.target.closest('[data-retry]')){accountPromise=null;renderDownloads();}if(e.target.closest('[data-logout]')){try{await api('logout',{method:'POST'});accountPromise=null;accountEpoch++;favoriteRevision++;libraryGeneration++;libraryItems=[];saved=new Set();await refreshAccount();location.hash='downloads';render();}catch(e){toast(e.message);}}});
async function refreshAccount(){try{const a=await account();const link=document.querySelector('#account-link');link.textContent=a.user?a.user.login:'我的空间';if(a.user){const {profile}=await api('profile');link.innerHTML=avatarHTML(profile)+`<span>${escape(profile.name)}</span>`;await loadFavorites();}document.querySelector('[data-review-link]').hidden=!a.reviewer;document.querySelector('.publish-link').textContent=a.creator?.status==='approved'?'发布作品':'成为创作者';document.querySelector('[data-creator-review-link]').hidden=!a.reviewer;link.setAttribute('aria-label','个人菜单');document.querySelector('.account-menu [data-logout]').hidden=!a.user;}catch{}}
refreshAccount();
if(new URLSearchParams(location.search).get('login')==='failed'){const reason=new URLSearchParams(location.search).get('reason');const messages={bad_verification_code:'授权已过期，请重新登录。',incorrect_client_credentials:'登录应用的密钥配置不匹配。',redirect_uri_mismatch:'登录回调地址不匹配。',token_exchange:'暂时无法连接 GitHub 登录服务。',token_exchange_failed:'GitHub 未能完成授权，请重新登录。',profile:'暂时无法读取 GitHub 公开身份。',database:'账号保存失败，请稍后重试。'};toast(messages[reason]||'登录未完成，请再试一次。');}

Promise.all([loadPublished(),loadDiscovery()]).finally(()=>{render();resumePendingDownload();});


function avatarHTML(p){return (p.customAvatar||p.avatar==='github')&&p.avatarUrl?`<img class="user-avatar" src="${escape(p.avatarUrl)}" alt="" referrerpolicy="no-referrer">`:`<span class="user-avatar avatar-${escape(p.avatar)}">${escape(p.name.slice(0,1))}</span>`;}
function localLink(){return ['127.0.0.1','localhost'].includes(location.hostname)?'<p><a class="pill" href="https://ccbcm.net/#settings">前往正式网站</a></p>':'';}
async function renderPersonal(page){
 const titles={studio:'创作中心',me:'个人主页',settings:'账号设置'};
 app.innerHTML=`<section class="intro-line"><h1>${titles[page]}</h1></section><div id="personal-body">正在读取…</div>`;
 try{const a=await account();if(route!==page)return;const body=document.querySelector('#personal-body');if(!a.user){body.innerHTML=loginPanel(a.ready);return;}
 if(page==='studio'){if(a.creator?.status!=='approved'){renderCreatorApplication(body,a.creator);return;}await renderDrafts(body);return;}
 const {profile:p}=await api('profile');if(route!==page)return;
 if(page==='me'){location.hash='people/'+p.login;return;}
 body.innerHTML=`<form id="profile-form" class="profile-form"><div class="profile-preview">${avatarPicker(p)}<div><h2>${escape(p.name)}</h2><p>GitHub · ${escape(p.login)}</p></div></div><label>昵称<input name="name" value="${escape(p.name)}" maxlength="40" required></label><label>简介<textarea name="bio" maxlength="300" rows="2" placeholder="介绍一下你自己，或喜欢的创作。">${escape(p.bio)}</textarea></label><input type="hidden" name="avatar" value="${escape(p.avatar)}"><p class="subtitle">昵称、头像和简介会展示在你的公开主页。下载和收藏仅自己可见。</p><div class="detail-actions"><button class="pill" type="submit">保存资料</button><a class="pill secondary" href="#people/${escape(p.login)}">查看公开主页</a></div><p id="profile-status" role="status"></p></form>`;growBio();
 }catch(e){if(route===page)document.querySelector('#personal-body').innerHTML=`<div class="empty">${escape(e.message)}${localLink()}<button class="pill secondary" data-personal-retry>重试</button></div>`;}
}
async function renderPublic(login){const expected=route;app.innerHTML='<div class="empty">正在读取主页…</div>';try{const {profile:p}=await api('people/'+encodeURIComponent(login));if(route!==expected)return;const viewer=(await account()).user;const owner=viewer?.login?.toLowerCase()===p.login.toLowerCase();if(route!==expected)return;app.innerHTML=`<section class="profile">${owner?avatarPicker(p):avatarHTML(p)}<div><h1>${escape(p.name)}</h1><p class="bio">${escape(p.bio||'还没有填写简介。')}</p><p class="subtitle">@${escape(p.login)}</p></div></section>${owner&&String(viewer.id)==='325610429'?'<section class="upload-panel"><h2>陆家嘴 · 城市漫游</h2><p>仅自己可见</p><div class="detail-actions"><a class="pill secondary" href="/city.html">打开作品 ↗</a></div></section>':''}<h2>公开作品</h2><div class="grid public-grid">${works.filter(w=>w.ownerLogin?.toLowerCase()===p.login.toLowerCase()||!w.uploaded&&p.login.toLowerCase()==='ccbcm'&&w.author==='ccbcm').map(card).join('')||'<div class="empty">还没有发布作品。</div>'}</div>`;}catch(e){if(route===expected)app.innerHTML=`<div class="empty">${escape(e.message)}${localLink()}<a class="pill secondary" href="#creators">返回创作者</a></div>`;}}
function paintHearts(){document.querySelectorAll('[data-save]').forEach(el=>{const w=works.find(w=>w.id===el.dataset.save);if(!w)return;const on=saved.has(w.id);el.classList.toggle('selected',on);el.textContent=on?'♥':'♡';el.setAttribute('aria-pressed',String(on));el.setAttribute('aria-label',(on?'取消收藏':'收藏')+' '+w.name);el.disabled=favoriteJobs.has(w.id);el.setAttribute('aria-busy',String(el.disabled));});}
async function loadFavorites(){const revision=favoriteRevision,{items}=await api('favorites');if(revision!==favoriteRevision)return;saved=new Set(items.map(x=>x.id));for(const [id,on] of favoriteJobs)on?saved.add(id):saved.delete(id);paintHearts();}
async function toggleFavorite(button){const id=button.dataset.save;if(favoriteJobs.has(id))return;const epoch=accountEpoch,before=saved.has(id),desired=!before;favoriteJobs.set(id,desired);favoriteRevision++;desired?saved.add(id):saved.delete(id);paintHearts();if(route==='downloads')paintLibrary();
 try{const a=await account();if(epoch!==accountEpoch)return;if(!a.user){before?saved.add(id):saved.delete(id);dialog.close();location.hash='downloads';toast('登录后，就能留下喜欢的壁纸');return;}
 await api('favorites',{method:desired?'POST':'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});
 }catch(e){if(epoch!==accountEpoch)return;before?saved.add(id):saved.delete(id);toast('收藏未保存：'+e.message);if(e.status===401)accountPromise=null;}
 finally{favoriteJobs.delete(id);if(epoch===accountEpoch){favoriteRevision++;paintHearts();if(route==='downloads')paintLibrary();}}}
function legacyFavorites(){try{return [...new Set(JSON.parse(localStorage.getItem('ccbcm-saved')||'[]'))].filter(id=>works.some(w=>w.id===id));}catch{return []}}
function renderFavorites(){if(route==='downloads')return renderDownloads();location.hash='downloads';}

document.addEventListener('submit',async e=>{if(e.target.id!=='profile-form')return;e.preventDefault();const form=e.target,button=form.querySelector('button[type="submit"]'),status=form.querySelector('#profile-status');button.disabled=true;try{const b=Object.fromEntries(new FormData(form));await api('profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});status.textContent='资料已保存。';await refreshAccount();}catch(e){status.textContent=e.message;}finally{button.disabled=false;}});
document.addEventListener('click',async e=>{if(e.target.closest('[data-favorites-retry]')){accountPromise=null;renderFavorites();}const button=e.target.closest('[data-import-favorites]');if(!button)return;button.disabled=true;try{for(const id of legacyFavorites())await api('favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});localStorage.removeItem('ccbcm-saved');await renderFavorites();toast('旧收藏已导入当前账号');}catch(e){const status=document.querySelector('#import-status');if(status)status.textContent=e.message+' 旧记录已保留，可重试。';}finally{button.disabled=false;}});
document.addEventListener('click',e=>{if(e.target.closest('[data-personal-retry]')){accountPromise=null;renderPersonal(route)}if(!e.target.closest('.account-menu'))document.querySelector('.account-menu').open=false;});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('.account-menu').open=false;});

function growBio(){document.querySelectorAll('.profile-form textarea,.video-work textarea').forEach(el=>{el.style.height='auto';el.style.height=(el.scrollHeight+2)+'px';});}
document.addEventListener('input',e=>{if(e.target.matches('.profile-form textarea,.video-work textarea'))growBio();});
window.addEventListener('resize',growBio);
function avatarPicker(p){return `<label class="avatar-picker" title="更换头像">${avatarHTML(p)}<input type="file" accept="image/jpeg,image/png,image/webp" data-avatar-file aria-label="选择头像图片"><span class="avatar-status" role="status"></span></label>`;}
document.addEventListener('change',async e=>{
 const input=e.target;if(!input.matches('[data-avatar-file]')||!input.files.length)return;
 const label=input.closest('.avatar-picker'),status=label.querySelector('.avatar-status');input.disabled=true;let url;
 try{const file=input.files[0];if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('请选择 10 MB 以内的 JPG、PNG 或 WebP 图片。');
 status.textContent='正在上传…';url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(img.width*img.height>40000000)throw Error('图片尺寸太大，请缩小后再试。');
 const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const ctx=canvas.getContext('2d');ctx.fillStyle='#eeeeee';ctx.fillRect(0,0,256,256);const side=Math.min(img.width,img.height);ctx.drawImage(img,(img.width-side)/2,(img.height-side)/2,side,side,0,0,256,256);
 const image=canvas.toDataURL('image/jpeg',0.85);await api('avatar',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});
 const old=label.querySelector('.user-avatar'),replacement=document.createElement('img');replacement.className='user-avatar';replacement.alt='';replacement.src=image;old.replaceWith(replacement);status.textContent='已更新';await refreshAccount();toast('头像已更新');
 }catch(error){status.textContent=error.message;toast(error.message);}finally{if(url)URL.revokeObjectURL(url);input.disabled=false;input.value='';}
});

async function renderTextDrafts(body){const {items}=await api('drafts');if(route!=='studio')return;body.innerHTML=`<p class="subtitle">先记下作品想法。草稿仅自己可见，文件上传与正式发布正在接入。</p><p id="storage-status" class="subtitle" role="status">正在检查文件存储…</p><form id="draft-form" class="profile-form" method="post"><input type="hidden" name="id"><label>作品标题<input name="title" maxlength="100" required placeholder="给作品起个名字"></label><label>作品简介<textarea name="description" rows="4" maxlength="1500"></textarea></label><button class="pill" type="submit">保存草稿</button><button class="pill secondary" type="reset">新建草稿</button><p id="draft-status" role="status"></p></form><h2 class="draft-heading">我的草稿</h2><div id="draft-list">${items.map(d=>`<article class="draft-card"><h3>${escape(d.title)}</h3><p>${escape(d.description)}</p><button class="pill secondary" data-edit-draft="${escape(d.id)}">继续编辑</button></article>`).join('')||'<div class="empty">还没有草稿。</div>'}</div>`;body.querySelectorAll('[data-edit-draft]').forEach(button=>button.onclick=()=>{const d=items.find(x=>x.id===button.dataset.editDraft),form=body.querySelector('#draft-form');form.elements.id.value=d.id;form.elements.title.value=d.title;form.elements.description.value=d.description;form.elements.title.focus();growBio();});growBio();api('storage').then(result=>{const el=document.querySelector('#storage-status');if(el)el.textContent=result.ready?'文件存储已连接，上传功能正在接入。':'文件存储尚未连接。';}).catch(()=>{const el=document.querySelector('#storage-status');if(el)el.textContent='暂时无法连接文件存储，文字草稿仍可保存。';});}
document.addEventListener('submit',async e=>{if(!e.target.matches('#draft-form'))return;e.preventDefault();const form=e.target,button=form.querySelector('[type="submit"]');button.disabled=true;try{const b=Object.fromEntries(new FormData(form));await api('drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});if(route==='studio')await renderDrafts(document.querySelector('#personal-body'));toast('草稿已保存');}catch(error){form.querySelector('#draft-status').textContent=error.message;}finally{button.disabled=false;}});
document.addEventListener('click',async e=>{if(e.target.closest('[data-open-login]')){const sheet=e.target.closest('.account-panel').querySelector('[data-login-sheet]');if(sheet){sheet.showModal();sheet.querySelector('input')?.focus();}}if(e.target.closest('[data-close-login]')){e.target.closest('[data-login-sheet]').close();}const button=e.target.closest('[data-email-code]');if(!button)return;const form=button.closest('form'),email=form.elements.email.value.trim().toLowerCase(),status=form.querySelector('[role="status"]');button.disabled=true;try{const response=await fetch('/api/auth/email/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const data=await response.json();if(!response.ok)throw Error(data.error||'验证码发送失败。');status.textContent='验证码已发送，请查收邮件。';let seconds=60;button.textContent=seconds+' 秒后重试';const timer=setInterval(()=>{seconds--;button.textContent=seconds?seconds+' 秒后重试':'获取验证码';if(!seconds){clearInterval(timer);button.disabled=false;}},1000);}catch(error){status.textContent=error.message;button.disabled=false;}});
document.addEventListener('submit',async e=>{const form=e.target;if(!form.matches('#email-login-form'))return;e.preventDefault();const button=form.querySelector('[type="submit"]'),status=form.querySelector('[role="status"]');button.disabled=true;try{const response=await fetch('/api/auth/email/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.elements.email.value.trim().toLowerCase(),code:form.elements.code.value.trim()})});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'邮箱登录失败。');location.hash='downloads';location.reload();}catch(error){status.textContent=error.message;button.disabled=false;}});



let videoUploadBusy=false;
const videoState={reserved:'等待上传',uploading:'上传处理中',failed:'上传未完成',verifying:'正在校验文件',ready:'壁纸已保存 · 未发布',review:'已提交审核 · 尚未公开',approved:'审核通过 · 可以上架',published:'已公开发布',unlisted:'已下架 · 修改后可重新提交审核'};
async function renderDrafts(body){
 const data=await api('videos');if(route!=='studio')return;
 body.innerHTML=`<section class="upload-panel"><h2>上传壁纸</h2><p>一张图片，或一段动态风景。上传后填写介绍，再提交审核。</p><label class="pill video-pick">选择图片或视频<input type="file" accept="video/mp4,video/quicktime,video/webm,video/x-matroska,image/png,image/jpeg,.mp4,.mov,.webm,.mkv,.png,.jpg,.jpeg" data-new-video aria-label="选择图片或视频" ${videoUploadBusy?'disabled':''}></label><p class="upload-hint">支持 MP4、MOV、WebM、MKV、PNG、JPG · 单个文件最多 200 MB</p><progress id="video-progress" value="0" max="100" hidden></progress><p id="video-upload-status" role="status"></p></section><h2 class="draft-heading">我的壁纸</h2><section class="video-library">${data.items.map(v=>`<article class="video-work" data-video-card="${v.id}">${['ready','review','approved','published','unlisted'].includes(v.state)?wallpaperPreview(v,'/api/videos/'+v.id+'/content'):`<div class="empty">${videoState[v.state]||'处理中'}</div>`}<form data-video-form="${v.id}" method="post"><label>作品标题<input name="title" maxlength="100" required value="${escape(v.title)}" ${['review','approved','published'].includes(v.state)?'disabled':''}></label><label>作品简介<textarea name="description" maxlength="1500" rows="3" ${['review','approved','published'].includes(v.state)?'disabled':''}>${escape(v.description)}</textarea></label><p class="subtitle">${videoState[v.state]||v.state} · ${(v.size/1024/1024).toFixed(1)} MB</p><div class="detail-actions">${!['review','approved','published'].includes(v.state)?'<button class="pill secondary" type="submit">保存信息</button>':''}${['ready','unlisted'].includes(v.state)?`<label class="pill secondary video-pick">选择高清封面<input type="file" accept="image/jpeg,image/png" data-cover-work="${v.id}" aria-label="选择高清封面"></label><button class="pill" type="button" data-submit-video="${v.id}">提交发布审核</button>`:''}${['failed','reserved','uploading','verifying'].includes(v.state)?`<label class="pill secondary video-pick">重新选择原文件重试<input type="file" accept="video/mp4,video/quicktime,video/webm,video/x-matroska,image/png,image/jpeg,.mp4,.mov,.webm,.mkv,.png,.jpg,.jpeg" data-retry-video="${v.id}" aria-label="重新选择 ${escape(v.title)}"></label>`:''}${v.state==='approved'?`<button class="pill" type="button" data-publish-video="${v.id}">公开上架</button>`:''}${v.state==='published'?`<button class="pill secondary" type="button" data-unlist-video="${v.id}">下架作品</button>`:''}<button class="text-button" type="button" data-remove-video="${v.id}">移除作品</button></div><p class="video-feedback" role="status">${['ready','unlisted'].includes(v.state)&&v.review_reason?'审核说明：'+escape(v.review_reason):''}</p></form></article>`).join('')||'<div class="empty">还没有作品，先选一张图片或一段视频吧。</div>'}</section><details class="legacy-drafts"><summary>之前保存的文字草稿</summary><div id="legacy-drafts-body"></div></details>`;
 growBio();body.querySelector('.legacy-drafts').addEventListener('toggle',async e=>{if(e.target.open&&!body.querySelector('#legacy-drafts-body').textContent)try{await renderTextDrafts(body.querySelector('#legacy-drafts-body'));}catch(error){body.querySelector('#legacy-drafts-body').textContent=error.message;}});
}
function wallpaperPreview(v,url){const poster=(v.poster||'').replace(/^\/api\/published-videos\/([a-f0-9]+)\/cover/,url.replace(/\/content$/, '/cover'));return v.mime?.startsWith('image/')?`<img class="wallpaper-preview" loading="lazy" src="${url}" alt="${escape(v.title)}">`:`<video class="wallpaper-preview" controls loop playsinline preload="none" poster="${escape(poster)}" src="${url}" aria-label="${escape(v.title)}"></video>`;}
function uploadPart(id,n,uploadId,blob,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT','/api/videos/'+id+'/part?n='+n);xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.setRequestHeader('X-Upload-Id',uploadId);xhr.timeout=5*60000;xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(e.loaded);};xhr.onerror=()=>reject(Error('网络中断，请重新选择原文件重试。'));xhr.ontimeout=()=>reject(Error('上传超时，请稍后重试。'));xhr.onload=()=>{let data;try{data=JSON.parse(xhr.responseText)}catch{reject(Error('服务器未正确响应，请重试。'));return;}if(xhr.status>=200&&xhr.status<300)resolve(data);else reject(Error(data.error||'上传失败，请重试。'));};xhr.send(blob);});}
async function uploadVideoBytes(id,file,onProgress){const state=await api('videos/'+id+'/begin',{method:'POST'});if(state.ready)return;for(let offset=0,n=1;offset<file.size;offset+=state.partSize,n++){const end=Math.min(file.size,offset+state.partSize);if(!state.parts[n])await uploadPart(id,n,state.uploadId,file.slice(offset,end),loaded=>onProgress(Math.floor((offset+loaded)/file.size*100)));onProgress(Math.floor(end/file.size*100));}
 // Completion is retryable: a timed-out request may have finished server-side.
 const waitForState=async()=>{for(let i=0;i<24;i++){const result=await api('videos');const item=result.items?.find(v=>v.id===id);if(item&&['ready','review','approved','published','unlisted'].includes(item.state))return {ok:true};if(item?.state==='failed')throw Error('文件校验未通过，请检查文件是否完整后重试。');await new Promise(r=>setTimeout(r,5000));}throw Error('云端校验仍在进行，请稍后回到创作中心查看结果。');};
 for(let attempt=0;attempt<3;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),180000);try{const response=await fetch('/api/videos/'+id+'/complete',{method:'POST',signal:controller.signal});let data;try{data=await response.json();}catch{data=null;}if(response.ok)return data;if(response.status===409&&data?.error?.includes('正在校验'))return await waitForState();throw Error(data?.error||'保存失败，请重试。');}catch(error){if(error.name==='AbortError'){try{return await waitForState();}catch(e){if(attempt===2)throw e;}}else if(attempt===2)throw error;await new Promise(r=>setTimeout(r,3000));}finally{clearTimeout(timer);}}
 return await waitForState();}
async function startVideoUpload(input){if(videoUploadBusy||!input.files.length)return;videoUploadBusy=true;input.disabled=true;const status=document.querySelector('#video-upload-status'),progress=document.querySelector('#video-progress');let id=input.dataset.retryVideo;
 try{const file=input.files[0],ext=file.name.split('.').pop().toLowerCase(),mime=({mp4:'video/mp4',mov:'video/quicktime',webm:'video/webm',mkv:'video/x-matroska',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg'})[ext];if(!mime||file.size>200*1024*1024||file.size<32)throw Error('请选择 200 MB 以内的 MP4、MOV、WebM、MKV、PNG 或 JPG。');status.textContent='正在提取高清封面…';let cover=null;try{cover=await extractCover(file);}catch(e){if(mime.startsWith('image/'))throw e;toast(e.message);}const poster='';
 const sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('');
 if(id){const {items}=await api('videos');const original=items.find(v=>v.id===id);if(!original||original.size!==file.size||original.sha256!==sha256)throw Error('请选择与上次相同的原文件。');}
 else{const record=await api('videos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:file.name.replace(/\.[^.]+$/,'').slice(0,100),size:file.size,sha256,poster,mime})});id=record.id;}
 progress.hidden=false;progress.value=0;status.textContent='正在上传…';await uploadVideoBytes(id,file,percent=>{progress.value=percent;status.textContent=percent===100?'正在校验并保存壁纸…':`正在上传 ${percent}%`;});if(cover)await api('videos/'+id+'/cover',{method:'PUT',headers:{'Content-Type':'image/jpeg','X-Media-Width':String(cover.width),'X-Media-Height':String(cover.height)},body:cover.blob});status.textContent='壁纸已保存到云端。';toast(cover?'壁纸与高清封面已保存':'原视频已保存，请补充封面');if(route==='studio')await renderDrafts(document.querySelector('#personal-body'));
 }catch(error){status.textContent=error.message+(id?' 可重新选择原文件继续上传。':'');if(id)input.dataset.retryVideo=id;toast(error.message);}finally{videoUploadBusy=false;input.disabled=false;input.value='';const pick=document.querySelector('[data-new-video]');if(pick)pick.disabled=false;}
}
document.addEventListener('change',e=>{if(e.target.matches('[data-new-video],[data-retry-video]'))startVideoUpload(e.target);});
document.addEventListener('change',async e=>{const input=e.target;if(!input.matches('[data-cover-work]')||!input.files.length)return;input.disabled=true;try{const cover=await extractCover(input.files[0]);await api('videos/'+input.dataset.coverWork+'/cover',{method:'PUT',headers:{'Content-Type':'image/jpeg','X-Media-Width':String(cover.width),'X-Media-Height':String(cover.height)},body:cover.blob});toast('高清封面已保存');if(route==='studio')await renderDrafts(document.querySelector('#personal-body'));}catch(error){toast(error.message);}finally{input.disabled=false;input.value='';}});
async function saveVideoInfo(form){return api('videos/'+form.dataset.videoForm,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});}
document.addEventListener('submit',async e=>{if(!e.target.matches('[data-video-form]'))return;e.preventDefault();const form=e.target,button=form.querySelector('[type=submit]');button.disabled=true;try{await saveVideoInfo(form);form.querySelector('.video-feedback').textContent='作品信息已保存。';}catch(error){form.querySelector('.video-feedback').textContent=error.message;}finally{button.disabled=false;}});
document.addEventListener('click',async e=>{const submit=e.target.closest('[data-submit-video]'),remove=e.target.closest('[data-remove-video]');if(!submit&&!remove)return;const button=submit||remove,form=button.closest('form');if(remove&&!confirm('移除这件云端作品？文件将被删除，已提交的审核也会撤回。'))return;button.disabled=true;try{if(submit){await saveVideoInfo(form);await api('videos/'+submit.dataset.submitVideo+'/submit',{method:'POST'});toast('已提交审核，尚未公开发布');}else await api('videos/'+remove.dataset.removeVideo,{method:'DELETE'});if(route==='studio')await renderDrafts(document.querySelector('#personal-body'));}catch(error){form.querySelector('.video-feedback').textContent=error.message;}finally{button.disabled=false;}});

async function renderModeration(){
 app.innerHTML='<section class="intro-line"><h1>作品审核</h1><a class="pill secondary" href="#reports">用户举报</a></section><div id="review-body">正在读取…</div>';
 try{const data=await api('moderation');if(route!=='moderation')return;
 document.querySelector('#review-body').innerHTML='<p class="subtitle">查看所有创作者提交的壁纸。通过后，作者即可公开上架。</p><section class="video-library">'+(data.items.map(v=>`<article class="video-work">${wallpaperPreview(v,'/api/moderation/'+v.id+'/content')}<div class="video-copy"><h2>${escape(v.title)}</h2><a href="#people/${escape(v.login)}">@${escape(v.login)}</a><p>${escape(v.description)}</p><p>${escape(videoState[v.state]||v.state)}</p>${['review','published'].includes(v.state)?`<form data-review-form="${v.id}"><label>审核说明<textarea name="reason" maxlength="500" rows="2" placeholder="退回时请告诉作者需要修改什么"></textarea></label><div class="detail-actions">${v.state==='published'?'<button class="pill secondary" type="submit" value="unlist">下架作品</button>':'<button class="pill" type="submit" value="approve">通过审核</button><button class="pill secondary" type="submit" value="reject">退回修改</button>'}</div><p role="status"></p></form>`:`<p>${escape(v.reason||'审核已完成')}</p>`}</div></article>`).join('')||'<div class="empty">暂时没有待审核的作品。</div>')+'</section>';
 }catch(e){if(route==='moderation')document.querySelector('#review-body').textContent=e.message;}
}
document.addEventListener('submit',async e=>{if(!e.target.matches('[data-review-form]'))return;e.preventDefault();const form=e.target,decision=e.submitter?.value,reason=form.elements.reason.value.trim();if(decision!=='approve'&&!reason){form.querySelector('[role=status]').textContent='请填写退回或下架原因。';return;}form.querySelectorAll('button').forEach(x=>x.disabled=true);try{await api('moderation/'+form.dataset.reviewForm,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,reason})});toast(decision==='approve'?'已通过审核':decision==='unlist'?'作品已下架，作者可查看原因':'已退回，作者可查看原因');await renderModeration();}catch(error){form.querySelector('[role=status]').textContent=error.message;}finally{form.querySelectorAll('button').forEach(x=>x.disabled=false);}});

async function loadPublished(){try{const [{items},legacyCovers]=await Promise.all([api('published-videos'),fetch('/gallery/media/hd/index.json').then(r=>r.ok?r.json():{}).catch(()=>({}))]);document.querySelector('#connection-status')?.remove();for(let i=works.length-1;i>=0;i--)if(works[i].uploaded)works.splice(i,1);for(const v of items)works.push({id:v.id,name:v.title,text:v.description,poster:v.poster?.startsWith('/api/')?v.poster:(legacyCovers[v.id]?.poster||v.poster),width:v.width||legacyCovers[v.id]?.width,height:v.height||legacyCovers[v.id]?.height,cover:'blue.jpg',ownerLogin:v.login,author:'account:'+v.login,mime:v.mime||'video/mp4',type:v.mime?.startsWith('image/')?'静态壁纸':'动态壁纸',tag:v.mime?.startsWith('image/')?'图片':'视频',original:v.login,uploaded:true,content:'/api/published-videos/'+v.id+'/content',video:v.mime?.startsWith('image/')?null:'/api/published-videos/'+v.id+'/content'});}catch(e){toast('公开作品暂时无法读取，可在页面内重试。');document.querySelector('#connection-status')?.remove();const status=document.createElement('div');status.id='connection-status';status.className='empty';status.innerHTML='部分作品暂未加载 <button class="pill secondary" data-catalog-retry>重试</button>';app.before(status);}}
function openUploaded(w){document.querySelector('#detail-body').innerHTML=`<div class="detail-cover">${wallpaperPreview({mime:w.mime,title:w.name,poster:image(w)},w.content)}</div><div class="detail-copy"><h2>${escape(w.name)}</h2><a class="author" href="#people/${escape(w.ownerLogin)}">@${escape(w.ownerLogin)}</a><p>${escape(w.text)}</p><button class="pill" data-download="${w.id}">下载</button>${heart(w)}${w.uploaded?`<form data-report-work="${w.id}" class="report-form"><details><summary>举报作品</summary><label>举报原因<textarea name="reason" maxlength="500" required></textarea></label><button class="pill secondary" type="submit">提交举报</button><p role="status"></p></details></form>`:''}</div>`;dialog.showModal();}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-publish-video],[data-unlist-video]');if(!b)return;b.disabled=true;try{const id=b.dataset.publishVideo||b.dataset.unlistVideo;await api('videos/'+id+(b.dataset.publishVideo?'/publish':'/unlist'),{method:'POST'});await loadPublished();if(route==='studio')await renderDrafts(document.querySelector('#personal-body'));toast(b.dataset.publishVideo?'作品已公开上架':'作品已下架');}catch(error){toast(error.message);}finally{b.disabled=false;}});

async function renderReports(){app.innerHTML='<h1>用户举报</h1><div id="reports-body">正在读取…</div>';try{const {items}=await api('moderation/reports');if(route!=='reports')return;document.querySelector('#reports-body').innerHTML=items.map(r=>`<article class="draft-card"><h2>${escape(r.title||'已移除作品')}</h2><p>举报人：${escape(r.login)}</p><p>${escape(r.reason)}</p><p>${r.state==='open'?'待处理':'已处理'}</p><a href="#moderation">前往作品审核</a>${r.state==='open'?`<button class="pill secondary" data-close-report="${r.id}">标记已处理</button>`:''}</article>`).join('')||'<p>暂时没有举报。</p>';}catch(e){if(route==='reports')document.querySelector('#reports-body').textContent=e.message;}}
document.addEventListener('submit',async e=>{if(!e.target.matches('[data-report-work]'))return;e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{await api('reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:f.dataset.reportWork,reason:f.elements.reason.value})});f.querySelector('[role=status]').textContent='已收到举报，管理员会查看。';}catch(error){f.querySelector('[role=status]').textContent=error.message;}finally{b.disabled=false;}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-close-report]');if(!b)return;b.disabled=true;try{await api('moderation/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:b.dataset.closeReport})});await renderReports();}catch(error){toast(error.message);b.disabled=false;}});

document.addEventListener('click',e=>{const a=e.target.closest('[data-apply-wallpaper]');if(!a)return;if(mobileDevice()){e.preventDefault();const id=a.getAttribute('href').split('/').pop(),w=works.find(w=>w.id===id);if(w)mobileUse(w,dialog,escape);return;}const card=a.closest('article');let hint=card.querySelector('.apply-feedback');if(!hint){hint=document.createElement('p');hint.className='apply-feedback subtitle';hint.setAttribute('role','status');card.querySelector('.download-info, .video-copy').appendChild(hint);}hint.replaceChildren(document.createTextNode('请允许浏览器打开 CCBCM 插件，壁纸会自动应用。没有反应？'));const link=document.createElement('a');link.href='#plugin';link.textContent='安装或更新插件';hint.appendChild(link);});

document.addEventListener('click',async e=>{const b=e.target.closest('[data-remove-download]');if(!b)return;b.disabled=true;try{await api('downloads',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:b.dataset.removeDownload})});if(route==='downloads')await renderDownloads();toast(saved.has(b.dataset.removeDownload)?'下载已移除，收藏仍保留':'已移除下载');}catch(error){toast(error.message);b.disabled=false;}});

function downloadCard(w,id,downloaded=true){const usable=w&&(w.video||w.type==='静态壁纸'),compatible=w&&(mobileLayout()?portraitWork(w):!portraitWork(w)),author=w?(w.ownerLogin||creators[w.author]?.name||'作者'):'作品不可用',type=w?(w.video?'视频动态壁纸':'静态壁纸'):'已下架或暂不可用';return `<article class="card download-card">${w?`<button class="cover" data-work="${w.id}" aria-label="查看 ${escape(w.name)}"><img loading="lazy" src="${image(w)}" alt="${escape(w.name)}"></button>`:'<div class="cover unavailable-cover">作品暂不可用</div>'}<div class="download-info"><div class="library-title"><h3 title="${escape(w?.name||'不可用作品')}">${escape(w?.name||'不可用作品')}</h3>${w?heart(w):`<button class="heart ${saved.has(id)?'selected':''}" data-save="${id}" aria-label="取消收藏" aria-pressed="${saved.has(id)}">${saved.has(id)?'♥':'♡'}</button>`}</div>${w?`<a class="author" title="${escape(author)}" href="#${w.ownerLogin?'people/'+escape(w.ownerLogin):'creator/'+w.author}">作者 · ${escape(author)}</a>`:`<span class="author">${author}</span>`}<p class="download-kind">${escape(type)}${downloaded?'':' · 未下载'}</p><div class="download-actions">${usable?(downloaded?(compatible?`<a class="pill" data-apply-wallpaper href="${mobileDevice()?'ccbcm-mobile':'ccbcm-wallpaper'}://apply/${id}">使用</a>`:''):`<button class="pill" data-download="${id}">下载</button>`):'<button class="pill" disabled>暂不可用</button>'}${downloaded?`<button class="text-button" data-remove-download="${id}">移除下载</button>`:'<span class="library-save-note">已收藏</span>'}</div></div></article>`;}


document.addEventListener('click',async e=>{const b=e.target.closest('[data-catalog-retry]');if(!b)return;b.disabled=true;try{await loadPublished();render();}finally{b.disabled=false;}});

function renderCreatorApplication(body,access={status:'none'}){const pending=access.status==='pending';body.innerHTML=`<section class="creator-application"><h2>${pending?'申请已提交':'成为创作者'}</h2><p>${pending?'CCBCM 会查看你的申请，审核通过后就能上传作品。':'先介绍一下你想分享的作品，通过审核后即可上传和发布。浏览、收藏和使用壁纸不受影响。'}</p>${access.reason?`<p class="application-reason">审核说明：${escape(access.reason)}</p>`:''}${pending?'':`<form id="creator-application-form"><label>创作介绍<textarea name="note" rows="4" maxlength="500" required placeholder="想分享什么类型的壁纸？也可以附上你的作品链接。"></textarea></label><button class="pill" type="submit">提交申请</button><p role="status"></p></form>`}<button class="text-button" data-access-refresh>刷新状态</button></section>`;}
async function renderCreatorReview(){app.innerHTML='<section class="intro-line"><h1>创作者申请</h1></section><section id="creator-applications" class="video-library">正在读取…</section>';try{const {items}=await api('creator-applications');if(route!=='creator-review')return;document.querySelector('#creator-applications').innerHTML=items.map(x=>`<article class="creator-application"><h2 title="${escape(x.login)}">${escape(x.login)}</h2><details class="application-note"><summary>查看创作介绍</summary><p>${escape(x.note)}</p></details><p class="subtitle">${({pending:'等待审核',approved:'已通过',rejected:'已退回'})[x.status]}</p>${x.status==='pending'?`<form data-creator-decision="${escape(x.user_id)}"><label>审核说明<textarea name="reason" rows="2" maxlength="500" placeholder="退回时填写原因"></textarea></label><div class="detail-actions"><button class="pill" type="submit" value="approved">通过申请</button><button class="pill secondary" type="submit" value="rejected">退回修改</button></div><p role="status"></p></form>`:`<p>${escape(x.reason)}</p>`}</article>`).join('')||'<div class="empty">暂时没有创作者申请。</div>';}catch(e){if(route==='creator-review')document.querySelector('#creator-applications').innerHTML=`<div class="empty">${escape(e.message)}<button class="pill secondary" data-access-review-retry>重试</button></div>`;}}
document.addEventListener('submit',async e=>{const form=e.target;if(form.id!=='creator-application-form'&&!form.matches('[data-creator-decision]'))return;e.preventDefault();const button=e.submitter;button.disabled=true;try{if(form.id==='creator-application-form'){await api('creator-application',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:new FormData(form).get('note')})});accountPromise=null;await refreshAccount();renderPersonal('studio');}else{await api('creator-applications/'+encodeURIComponent(form.dataset.creatorDecision),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:button.value,reason:new FormData(form).get('reason')})});renderCreatorReview();}}catch(error){form.querySelector('[role="status"]').textContent=error.message;}finally{button.disabled=false;}});
document.addEventListener('click',async e=>{if(e.target.closest('[data-access-refresh]')){accountPromise=null;await refreshAccount();renderPersonal('studio');}if(e.target.closest('[data-access-review-retry]'))renderCreatorReview();});

document.addEventListener('input',e=>{if(e.target.matches('.creator-application textarea')){e.target.style.height='auto';e.target.style.height=e.target.scrollHeight+'px';}});

async function renderCreators(){app.innerHTML='<section class="intro-line"><div><h1>看看谁在创作</h1><p class="subtitle">从一件喜欢的作品，认识它背后的人。</p></div></section><section class="creators-grid" id="creator-directory">正在读取…</section>';try{const {items}=await api('creators');if(route!=='creators')return;document.querySelector('#creator-directory').innerHTML=items.length?items.map(p=>`<article class="creator-card live-creator">${avatarHTML(p)}<h2 title="${escape(p.name)}">${escape(p.name)}</h2><span class="subtitle">${p.publishedCount} 件公开作品</span><p title="${escape(p.bio)}">${escape(p.bio||'还没有填写简介。')}</p><a class="pill secondary" href="#people/${encodeURIComponent(p.login)}">看看作品 ↗</a></article>`).join(''):'<div class="empty">创作者们正在准备作品。</div>';}catch(error){if(route==='creators')document.querySelector('#creator-directory').innerHTML=`<div class="empty">${escape(error.message)}<button class="pill secondary" data-creators-retry>重试</button></div>`;}}
document.addEventListener('click',e=>{if(e.target.closest('[data-creators-retry]'))renderCreators();});

async function loadDiscovery(){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),3000);try{const response=await fetch('/api/discovery',{signal:controller.signal});if(response.ok){const data=await response.json();discoveryRanking=Array.isArray(data.items)?data.items:[];}}catch{}finally{clearTimeout(timer)}}
const clickedToday=new Set();
function recordClick(id){const key=Math.floor((Date.now()+8*3600000)/86400000)+':'+id;if(clickedToday.has(key))return;clickedToday.add(key);api('discovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})}).catch(()=>clickedToday.delete(key));}

setInterval(()=>{if(!document.hidden)loadDiscovery();},300000);
async function resumePendingDownload(){let pending;try{pending=JSON.parse(sessionStorage.getItem('ccbcm-pending-download')||'null');}catch{return;}if(!pending)return;if(Date.now()-pending.at>15*60000||!works.some(w=>w.id===pending.id)){try{sessionStorage.removeItem('ccbcm-pending-download');}catch{}return;}try{const a=await account();if(!a.user)return;await api('downloads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:pending.id})});sessionStorage.removeItem('ccbcm-pending-download');toast('已加入我的下载');if(pending.returnTo&&/^(discover|wallpapers|people\/[a-zA-Z0-9-]+|creator\/[a-zA-Z0-9-]+)$/.test(pending.returnTo)&&route!==pending.returnTo)location.hash=pending.returnTo;else if(route==='downloads')renderDownloads();}catch{toast('上次选择的壁纸暂未保存，请在作品中重新点击下载。');}}

