const creators={ccbcm:{name:'CCBCM',letter:'C',note:'我的创作角落。先从一座可以走进去的城市开始。',kind:'站内创作者'},vanta:{name:'Teng Bao',letter:'T',note:'Vanta 动态背景的作者。这里收录的是开源作品，并非作者入驻。',kind:'开源作者',url:'https://github.com/tengbao/vanta'},daylin:{name:'Daylin Morgan',letter:'D',note:'用代码和柔和配色做壁纸。这里收录的是开源作品，并非作者入驻。',kind:'开源作者',url:'https://github.com/daylinmorgan/catppuccin-wallpapers'}};
const works=[
{id:"blue",name:"蓝色呼吸",author:"ccbcm",type:"动态壁纸",tag:"极简",cover:"blue.jpg",video:"/gallery/media/blue.mp4",text:"柔和的蓝色渐变，缓缓流动。下载后可在 CCBCM 插件中使用。",original:"CCBCM",source:"https://github.com/ccbcm/The-world",license:"CCBCM 原创演示"},
{id:'waves',name:'海面慢慢',author:'vanta',type:'动态壁纸',tag:'自然',cover:'waves.jpg',text:'不用去很远，也可以看一会儿海。缓缓起伏的波纹，跟随鼠标轻轻改变视角。',original:'Waves',source:'https://github.com/tengbao/vanta',license:'MIT'},
{id:'clouds',name:'云上散步',author:'vanta',type:'动态壁纸',tag:'自然',cover:'clouds.jpg',text:'把天空留在桌面上。云层缓慢向前，适合安静地陪你工作。',original:'Clouds',source:'https://github.com/tengbao/vanta',license:'MIT'},
{id:'net',name:'星点之间',author:'vanta',type:'动态壁纸',tag:'抽象',cover:'net.jpg',text:'点与线在深色背景中舒展。移动鼠标，可以和这片小小的星网互动。',original:'Net',source:'https://github.com/tengbao/vanta',license:'MIT'},
{id:'cat',name:'一只小猫',author:'daylin',type:'静态壁纸',tag:'极简',cover:'cat.svg',text:'一点柔和的颜色，和一只不打扰你的小猫。保留原作者的 SVG 壁纸，可直接下载。',original:'Cat',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'},
{id:'city',name:'陆家嘴 · 城市漫游',author:'ccbcm',type:'互动作品',tag:'城市',cover:'city.png',text:'从江面看看东方明珠和三座高楼，也可以走进街区。场景还在慢慢完善，先把这一段创作留在这里。',original:'制作中',source:'https://github.com/ccbcm/The-world',license:'各素材许可见工程说明'},
{id:'lines',name:'线条的秩序',author:'daylin',type:'静态壁纸',tag:'极简',cover:'lines.svg',text:'干净的线条，让桌面留一点空。来自 Catppuccin Wallpapers 的原始矢量作品。',original:'Lines',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'},
{id:'caffeine',name:'咖啡时间',author:'daylin',type:'静态壁纸',tag:'极简',cover:'caffeine.svg',text:'给工作间隙留一杯咖啡。简洁的分子图案，适合喜欢安静桌面的你。',original:'Caffeine',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'},
{id:'tux',name:'企鹅朋友',author:'daylin',type:'静态壁纸',tag:'极简',cover:'tux.svg',text:'熟悉的小企鹅，换上柔和的底色。来自原作者的开源壁纸系列。',original:'Tux',source:'https://github.com/daylinmorgan/catppuccin-wallpapers',license:'MIT'}];
const app=document.querySelector('#app'),dialog=document.querySelector('#detail');let saved=new Set();let filter='全部',query='',route='discover',toastTimer;
const image=w=>'/gallery/media/'+w.cover;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){let el=document.querySelector('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function heart(w){return `<button class="heart ${saved.has(w.id)?'selected':''}" data-save="${w.id}" aria-label="${saved.has(w.id)?'取消收藏':'收藏'} ${w.name}" aria-pressed="${saved.has(w.id)}">${saved.has(w.id)?'♥':'♡'}</button>`}
function card(w){return `<article class="card"><button class="cover" data-work="${w.id}" aria-label="查看 ${w.name}"><img src="${image(w)}" alt="${w.name}" loading="lazy" width="600" height="375"><span class="badge">${w.type==='动态壁纸'?'▷ ':w.type==='互动作品'?'◈ ':''}${w.type}</span></button><div class="card-info"><div><h3>${w.name}</h3><a class="author" href="#creator/${w.author}">${creators[w.author].name} ${w.author==='ccbcm'?'':'· 开源精选'}</a></div>${heart(w)}</div></article>`}
function toolbar(title,sub){return `<section class="intro-line"><div><h2>${title}</h2><div class="subtitle">${sub}</div></div><label class="search"><span aria-hidden="true">⌕</span><input id="search" aria-label="搜索作品" placeholder="搜壁纸、风格或作者" value="${escape(query)}" type="search"></label></section><div class="filters" role="group" aria-label="作品分类">${['全部','动态壁纸','静态壁纸','互动作品','极简','自然'].map(f=>`<button class="chip ${filter===f?'active':''}" data-filter="${f}" aria-pressed="${filter===f}">${f}</button>`).join('')}</div><section class="grid" id="grid" aria-label="作品"></section>`}
function renderGrid(){let list=works.filter(w=>(route!=='wallpapers'||w.type!=='互动作品')&&(route!=='saved'||saved.has(w.id))&&(!route.startsWith('creator/')||w.author===route.split('/')[1])&&(filter==='全部'||w.type===filter||w.tag===filter)&&(`${w.name} ${creators[w.author].name} ${w.tag} ${w.original}`).toLowerCase().includes(query.toLowerCase()));document.querySelector('#grid').innerHTML=list.length?list.map(card).join(''):`<div class="empty">${route==='saved'?'还没有收藏。遇到喜欢的作品，点一下 ♡ 就能留在这里。':'没有找到合适的作品，换个词试试。'}</div>`}
function render(){route=location.hash.slice(1)||'discover';filter='全部';query='';if(dialog.open)dialog.close();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route||route.startsWith('creator/')&&a.dataset.nav==='creators'));
document.querySelector('.account-menu').open=false;
if(route==='moderation'){renderModeration();return;}
if(route==='plugin'){app.innerHTML='<section class="intro-line"><div><h1>让桌面动起来</h1><p class="subtitle">安装一次，之后从桌面或托盘打开。</p></div></section>'+document.querySelector('#plugin-page').innerHTML;return;}
if(['studio','me','settings'].includes(route)){renderPersonal(route);return;}
if(route==='saved'){renderFavorites();return;}if(route.startsWith('people/')){renderPublic(route.slice(7));return;}if(!['discover','wallpapers','creators','downloads','saved'].includes(route)&&!route.startsWith('creator/')){app.innerHTML='<div class="empty"><h1>没有找到这个页面</h1><p>你可以回到发现，或从个人菜单进入自己的空间。</p><a class="pill" href="#discover">返回发现</a></div>';return;}
if(route==='downloads'){renderDownloads();return}
if(route==='creators'){app.innerHTML=`<section class="intro-line"><div><p class="eyebrow">PEOPLE & IDEAS</p><h1>看看谁在创作</h1><p class="subtitle">从一件喜欢的作品，认识它背后的人。</p></div></section><section class="creators-grid">${Object.entries(creators).map(([id,c])=>`<article class="creator-card"><span class="avatar">${c.letter}</span><h2>${c.name}</h2><span class="subtitle">${c.kind}</span><p>${c.note}</p><a class="pill secondary" href="#creator/${id}">看看作品 ↗</a></article>`).join('')}</section>`;return}
if(route.startsWith('creator/')){let c=creators[route.split('/')[1]];if(!c){app.innerHTML='<div class="empty">这个主页还不存在。<a href="#creators">返回创作者</a></div>';return}app.innerHTML=`<section class="profile"><span class="avatar">${c.letter}</span><div><p class="eyebrow">${c.kind}</p><h1>${c.name}</h1><p>${c.note}</p>${c.url?`<a class="author" href="${c.url}" target="_blank" rel="noopener">GitHub ↗</a>`:''}</div></section>`+toolbar('公开作品','这里只展示作者发布或注明来源的收录作品。');}
else{const isHome=route==='discover';app.innerHTML=(isHome?`<section class="hero"><div class="hero-copy"><p class="eyebrow">A LITTLE ESCAPE</p><h1>换个喜欢的风景。</h1><p>让桌面安静一点，也生动一点。<br>挑一张壁纸，看看创作者的世界。</p><a href="#wallpapers" class="pill">去逛逛 <span>↗</span></a></div><button class="hero-art" data-work="waves" aria-label="查看海面慢慢"><img src="/gallery/media/waves.jpg" alt="青蓝色起伏的海面" width="1400" height="850" fetchpriority="high"><div class="hero-label"><div><strong>海面慢慢</strong><small>Vanta · 动态壁纸</small></div><span class="play-circle">▷</span></div></button></section>`:'')+toolbar(route==='saved'?'留住喜欢的':route==='wallpapers'?'挑一张，陪你工作':'值得停留的风景',route==='saved'?'收藏保存在这台设备的浏览器里。':'先看封面，喜欢再点开。')+(isHome?`<section class="collection"><span class="orb">◈</span><div><h2>不止壁纸，还有一个小世界</h2><p>CCBCM 的陆家嘴，正在一点点长出来。</p></div><a class="pill secondary" href="#creator/ccbcm">看看 CCBCM 的作品 ↗</a></section>`:'');}
renderGrid();document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;renderGrid()});}
function openWork(id){let w=works.find(w=>w.id===id);if(!w)return;let dynamic=w.type==='动态壁纸';if(w.video){openVideo(w);return;}document.querySelector('#detail-body').innerHTML=`<div class="detail-cover"><img src="${image(w)}" alt="${w.name}">${dynamic?'<button class="pill start" id="start">▷ 播放预览</button>':''}</div><div class="detail-copy"><p class="eyebrow">${w.type} · ${w.tag}</p><h2>${w.name}</h2><a class="author" href="#creator/${w.author}">${creators[w.author].name} ↗</a><p>${w.text}</p><div class="detail-actions">${w.id==='city'?'<a class="pill" href="/city.html">进入城市 ↗</a>':`<button class="pill" data-download="${w.id}">下载</button>`}${heart(w)}</div><div class="meta"><span>${w.original}</span><span>${w.license}</span><span>${dynamic?'网页动态效果':w.id==='city'?'制作中 · 电脑体验更好':'SVG · 可缩放'}</span></div>${dynamic?'<p class="subtitle">这是网页动态效果，不是视频文件。用作桌面壁纸时，需要支持网页壁纸的软件。关闭预览后会停止运行。</p>':''}</div>`;dialog.showModal();document.querySelector('#start')?.addEventListener('click',()=>{document.querySelector('.detail-cover').innerHTML=`<iframe src="/gallery/preview.html?id=${id}" title="${w.name} 动态预览" sandbox="allow-scripts allow-same-origin"></iframe>`});}
document.addEventListener('click',e=>{let work=e.target.closest('[data-work]');if(work)openWork(work.dataset.work);let b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderGrid()}let save=e.target.closest('[data-save]');if(save)toggleFavorite(save);});

dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>document.querySelector('#detail-body').replaceChildren());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});document.querySelector('#about').onclick=()=>{document.querySelector('#detail-body').innerHTML='<div class="detail-copy"><p class="eyebrow">HELLO, CCBCM</p><h2>先放一些喜欢的作品。</h2><p>这里刚刚开始。现在可以浏览壁纸、播放预览、收藏作品，也可以看看 CCBCM 的三维城市。</p><p>开源精选保留原作者和来源，并非作者本人投稿。创作者注册、上传与发布功能还在准备中。</p><p>所有壁纸都需要主动点击才会播放。希望这里轻一点，也舒服一点。</p></div>';dialog.showModal()};


let accountPromise;
async function api(path,options={}){if(['127.0.0.1','localhost'].includes(location.hostname))throw Error('这是本地页面预览，账号功能请到 ccbcm.net 使用。');const r=await fetch('/api/'+path,{credentials:'same-origin',...options});let data;try{data=await r.json()}catch{throw Error('账号服务没有正确响应，请刷新重试。')}if(!r.ok)throw Object.assign(Error(data.error||'暂时无法完成，请重试。'),{status:r.status});return data;}
function account(){return accountPromise||(accountPromise=api('account').catch(error=>{accountPromise=null;throw error}));}
function loginPanel(ready){return `<div class="empty account-panel"><h2>${ready?'把喜欢的壁纸留在这里':'我的下载即将开放'}</h2><p>${ready?'登录 GitHub，下载的壁纸就会保存在你的账号中。':'GitHub 登录正在配置。壁纸可以正常浏览和预览。'}</p>${ready?'<a class="pill" href="/api/auth/github">使用 GitHub 登录</a>':''}</div>`;}
async function saveDownload(id){const w=works.find(w=>w.id===id);if(!w)return;try{const a=await account();if(!a.user){dialog.close();location.hash='downloads';return;}toast('正在保存…');await api('downloads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});toast('已保存到我的下载');dialog.close();if(route==='downloads')renderDownloads();else location.hash='downloads';}catch(e){toast(e.message);if(e.status===401)accountPromise=null;}}
async function renderDownloads(){app.innerHTML='<section class="intro-line"><div><h1>我的下载</h1><p class="subtitle">仅你可见 · 加入账号的壁纸。保存到电脑后才能离线使用。</p></div><a class="pill secondary" href="#wallpapers">去找壁纸 ↗</a></section><p class="subtitle">想放到桌面上？<a href="#plugin">安装或打开桌面插件</a></p><section class="grid" id="download-grid"><p>正在读取…</p></section>';try{const a=await account();if(route!=='downloads')return;const grid=document.querySelector('#download-grid');if(!a.user){grid.innerHTML=loginPanel(a.ready);return;}const {items}=await api('downloads');if(route!=='downloads')return;grid.innerHTML=`<div class="account-bar"><span>${escape(a.user.name)} 的下载</span><button class="text-button" data-logout>退出登录</button></div>`+(items.length?items.map(item=>{const w=works.find(w=>w.id===item.id);if(!w)return '';return `<article class="card download-card"><button class="cover" data-work="${w.id}" aria-label="查看 ${w.name}"><img src="${image(w)}" alt="${w.name}"></button><div class="download-info"><h3>${w.name}</h3><a class="author" href="#creator/${w.author}">作者 · ${creators[w.author].name}</a><p class="subtitle">${w.video?'视频动态壁纸':w.type==='动态壁纸'?'网页壁纸 · 当前插件暂不支持':'静态壁纸'}</p><div class="detail-actions">${w.video?`<a class="pill" href="ccbcm-wallpaper://apply/${w.id}">设为动态壁纸</a>`:''}<a class="pill secondary" href="${w.video|| (w.type==='动态壁纸'?'/downloads/'+w.id+'.zip':image(w))}" download>保存到电脑</a></div></div></article>`}).join(''):'<div class="empty">还没有下载壁纸。<br><a class="pill" href="#wallpapers">去找喜欢的壁纸 ↗</a></div>');}catch(e){if(route==='downloads')document.querySelector('#download-grid').innerHTML=`<div class="empty">${escape(e.message)}<br><button class="pill secondary" data-retry>重试</button></div>`;}}
function openVideo(w){document.querySelector('#detail-body').innerHTML=`<div class="detail-cover"><video controls muted loop playsinline preload="none" poster="${image(w)}" src="${w.video}" style="width:100%;height:100%;object-fit:cover"></video></div><div class="detail-copy"><p class="eyebrow">动态壁纸 · 极简</p><h2>${w.name}</h2><p>${w.text}</p><div class="detail-actions"><button class="pill" data-download="${w.id}">下载</button>${heart(w)}</div></div>`;dialog.showModal();}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-download]');if(b){e.preventDefault();b.disabled=true;try{await saveDownload(b.dataset.download)}finally{b.disabled=false;}}if(e.target.closest('[data-retry]')){accountPromise=null;renderDownloads();}if(e.target.closest('[data-logout]')){try{await api('logout',{method:'POST'});accountPromise=null;saved=new Set();await refreshAccount();location.hash='downloads';render();}catch(e){toast(e.message);}}});
async function refreshAccount(){try{const a=await account();const link=document.querySelector('#account-link');link.textContent=a.user?a.user.login:'我的空间';if(a.user){const {profile}=await api('profile');link.innerHTML=avatarHTML(profile)+`<span>${escape(profile.name)}</span>`;await loadFavorites();}document.querySelector('[data-review-link]').hidden=!a.reviewer;link.setAttribute('aria-label','个人菜单');document.querySelector('.account-menu [data-logout]').hidden=!a.user;}catch{}}
refreshAccount();
if(new URLSearchParams(location.search).get('login')==='failed'){const reason=new URLSearchParams(location.search).get('reason');const messages={bad_verification_code:'授权已过期，请重新登录。',incorrect_client_credentials:'登录应用的密钥配置不匹配。',redirect_uri_mismatch:'登录回调地址不匹配。',token_exchange:'暂时无法连接 GitHub 登录服务。',token_exchange_failed:'GitHub 未能完成授权，请重新登录。',profile:'暂时无法读取 GitHub 公开身份。',database:'账号保存失败，请稍后重试。'};toast(messages[reason]||'登录未完成，请再试一次。');}

render();


function avatarHTML(p){return (p.customAvatar||p.avatar==='github')&&p.avatarUrl?`<img class="user-avatar" src="${escape(p.avatarUrl)}" alt="" referrerpolicy="no-referrer">`:`<span class="user-avatar avatar-${escape(p.avatar)}">${escape(p.name.slice(0,1))}</span>`;}
function localLink(){return ['127.0.0.1','localhost'].includes(location.hostname)?'<p><a class="pill" href="https://ccbcm.net/#settings">前往正式网站</a></p>':'';}
async function renderPersonal(page){
 const titles={studio:'创作中心',me:'个人主页',settings:'账号设置'};
 app.innerHTML=`<section class="intro-line"><h1>${titles[page]}</h1></section><div id="personal-body">正在读取…</div>`;
 try{const a=await account();if(route!==page)return;const body=document.querySelector('#personal-body');if(!a.user){body.innerHTML=loginPanel(a.ready);return;}
 if(page==='studio'){await renderDrafts(body);return;}
 const {profile:p}=await api('profile');if(route!==page)return;
 if(page==='me'){location.hash='people/'+p.login;return;}
 body.innerHTML=`<form id="profile-form" class="profile-form"><div class="profile-preview">${avatarPicker(p)}<div><h2>${escape(p.name)}</h2><p>GitHub · ${escape(p.login)}</p></div></div><label>昵称<input name="name" value="${escape(p.name)}" maxlength="40" required></label><label>简介<textarea name="bio" maxlength="300" rows="2" placeholder="介绍一下你自己，或喜欢的创作。">${escape(p.bio)}</textarea></label><input type="hidden" name="avatar" value="${escape(p.avatar)}"><p class="subtitle">昵称、头像和简介会展示在你的公开主页。下载和收藏仅自己可见。</p><div class="detail-actions"><button class="pill" type="submit">保存资料</button><a class="pill secondary" href="#people/${escape(p.login)}">查看公开主页</a></div><p id="profile-status" role="status"></p></form>`;growBio();
 }catch(e){if(route===page)document.querySelector('#personal-body').innerHTML=`<div class="empty">${escape(e.message)}${localLink()}<button class="pill secondary" data-personal-retry>重试</button></div>`;}
}
async function renderPublic(login){const expected=route;app.innerHTML='<div class="empty">正在读取主页…</div>';try{const {profile:p}=await api('people/'+encodeURIComponent(login));if(route!==expected)return;const owner=(await account()).user?.login?.toLowerCase()===p.login.toLowerCase();if(route!==expected)return;app.innerHTML=`<section class="profile">${owner?avatarPicker(p):avatarHTML(p)}<div><h1>${escape(p.name)}</h1><p class="bio">${escape(p.bio||'还没有填写简介。')}</p><p class="subtitle">@${escape(p.login)}</p></div></section><h2>公开作品</h2><div class="grid public-grid">${p.login.toLowerCase()==='ccbcm'?works.filter(w=>w.author==='ccbcm').map(card).join(''):'<div class="empty">还没有发布作品。作品发布功能正在完善。</div>'}</div>`;}catch(e){if(route===expected)app.innerHTML=`<div class="empty">${escape(e.message)}${localLink()}<a class="pill secondary" href="#creators">返回创作者</a></div>`;}}
async function loadFavorites(){const {items}=await api('favorites');saved=new Set(items.map(x=>x.id));document.querySelectorAll('[data-save]').forEach(el=>{const w=works.find(w=>w.id===el.dataset.save);if(w)el.outerHTML=heart(w);});}
let favoriteBusy=false;
async function toggleFavorite(button){if(favoriteBusy)return;favoriteBusy=true;button.disabled=true;try{const a=await account();if(!a.user){dialog.close();location.hash='saved';return;}const id=button.dataset.save;await loadFavorites();await api('favorites',{method:saved.has(id)?'DELETE':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});await loadFavorites();toast(saved.has(id)?'已加入我的收藏':'已取消收藏');if(route==='saved')renderFavorites();}catch(e){toast(e.message)}finally{favoriteBusy=false;button.disabled=false;}}
function legacyFavorites(){try{return [...new Set(JSON.parse(localStorage.getItem('ccbcm-saved')||'[]'))].filter(id=>works.some(w=>w.id===id));}catch{return []}}
async function renderFavorites(){app.innerHTML='<section class="intro-line"><div><h1>我的收藏</h1><p class="subtitle">仅你可见 · 登录同一账号，可以在其他设备继续查看。</p></div></section><div id="favorites-body">正在读取…</div>';try{const a=await account();if(route!=='saved')return;if(!a.user){document.querySelector('#favorites-body').innerHTML=loginPanel(a.ready);return;}await loadFavorites();if(route!=='saved')return;const old=legacyFavorites();document.querySelector('#favorites-body').innerHTML=(old.length?`<section class="import-panel"><h2>这台浏览器还有 ${old.length} 件旧收藏</h2><p>确认这些是你的收藏，再导入到当前账号 @${escape(a.user.login)}。不会自动合并。</p><button class="pill secondary" data-import-favorites>导入到这个账号</button><p id="import-status" role="status"></p></section>`:'')+`<div class="grid">${works.filter(w=>saved.has(w.id)).map(card).join('')||'<div class="empty">还没有收藏。遇到喜欢的作品，点一下 ♡ 就能留在这里。</div>'}</div>`;}catch(e){if(route==='saved')document.querySelector('#favorites-body').innerHTML=`<div class="empty">${escape(e.message)}${localLink()}<button class="pill secondary" data-favorites-retry>重试</button></div>`;}}
document.addEventListener('submit',async e=>{if(e.target.id!=='profile-form')return;e.preventDefault();const form=e.target,button=form.querySelector('button[type="submit"]'),status=form.querySelector('#profile-status');button.disabled=true;try{const b=Object.fromEntries(new FormData(form));await api('profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});status.textContent='资料已保存。';await refreshAccount();}catch(e){status.textContent=e.message;}finally{button.disabled=false;}});
document.addEventListener('click',async e=>{if(e.target.closest('[data-favorites-retry]')){accountPromise=null;renderFavorites();}const button=e.target.closest('[data-import-favorites]');if(!button)return;button.disabled=true;try{for(const id of legacyFavorites())await api('favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});localStorage.removeItem('ccbcm-saved');await renderFavorites();toast('旧收藏已导入当前账号');}catch(e){const status=document.querySelector('#import-status');if(status)status.textContent=e.message+' 旧记录已保留，可重试。';}finally{button.disabled=false;}});
document.addEventListener('click',e=>{if(e.target.closest('[data-personal-retry]')){accountPromise=null;renderPersonal(route)}if(!e.target.closest('.account-menu'))document.querySelector('.account-menu').open=false;});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('.account-menu').open=false;});

function growBio(){document.querySelectorAll('.profile-form textarea,.video-work textarea').forEach(el=>{el.style.height='auto';el.style.height=(el.scrollHeight+2)+'px';});}
document.addEventListener('input',e=>{if(e.target.matches('.profile-form textarea,.video-work textarea'))growBio();});
window.addEventListener('resize',growBio);
function avatarPicker(p){return `<label class="avatar-picker" title="更换头像">${avatarHTML(p)}<input type="file" accept="image/jpeg,image/png,image/webp" data-avatar-file aria-label="选择头像图片"><span class="avatar-status" role="status"></span></label>`;}
document.addEventListener('change',async e=>{
 const input=e.target;if(!input.matches('[data-avatar-file]')||!input.files.length)return;
 const label=input.closest('.avatar-picker'),status=label.querySelector('.avatar-status');input.disabled=true;let url;
 try{const file=input.files[0];if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('请选择 10 MB 以内的 JPG、PNG 或 WebP 图片。');
 status.textContent='正在上传…';url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(img.width*img.height>40000000)throw Error('图片尺寸太大，请缩小后再试。');
 const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const ctx=canvas.getContext('2d');ctx.fillStyle='#eeeeee';ctx.fillRect(0,0,256,256);const side=Math.min(img.width,img.height);ctx.drawImage(img,(img.width-side)/2,(img.height-side)/2,side,side,0,0,256,256);
 const image=canvas.toDataURL('image/jpeg',0.85);await api('avatar',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});
 const old=label.querySelector('.user-avatar'),replacement=document.createElement('img');replacement.className='user-avatar';replacement.alt='';replacement.src=image;old.replaceWith(replacement);status.textContent='已更新';await refreshAccount();toast('头像已更新');
 }catch(error){status.textContent=error.message;toast(error.message);}finally{if(url)URL.revokeObjectURL(url);input.disabled=false;input.value='';}
});

async function renderTextDrafts(body){const {items}=await api('drafts');if(route!=='studio')return;body.innerHTML=`<p class="subtitle">先记下作品想法。草稿仅自己可见，文件上传与正式发布正在接入。</p><p id="storage-status" class="subtitle" role="status">正在检查文件存储…</p><form id="draft-form" class="profile-form" method="post"><input type="hidden" name="id"><label>作品标题<input name="title" maxlength="100" required placeholder="给作品起个名字"></label><label>作品简介<textarea name="description" rows="4" maxlength="1500"></textarea></label><button class="pill" type="submit">保存草稿</button><button class="pill secondary" type="reset">新建草稿</button><p id="draft-status" role="status"></p></form><h2 class="draft-heading">我的草稿</h2><div id="draft-list">${items.map(d=>`<article class="draft-card"><h3>${escape(d.title)}</h3><p>${escape(d.description)}</p><button class="pill secondary" data-edit-draft="${escape(d.id)}">继续编辑</button></article>`).join('')||'<div class="empty">还没有草稿。</div>'}</div>`;body.querySelectorAll('[data-edit-draft]').forEach(button=>button.onclick=()=>{const d=items.find(x=>x.id===button.dataset.editDraft),form=body.querySelector('#draft-form');form.elements.id.value=d.id;form.elements.title.value=d.title;form.elements.description.value=d.description;form.elements.title.focus();growBio();});growBio();api('storage').then(result=>{const el=document.querySelector('#storage-status');if(el)el.textContent=result.ready?'文件存储已连接，上传功能正在接入。':'文件存储尚未连接。';}).catch(()=>{const el=document.querySelector('#storage-status');if(el)el.textContent='暂时无法连接文件存储，文字草稿仍可保存。';});}
document.addEventListener('submit',async e=>{if(!e.target.matches('#draft-form'))return;e.preventDefault();const form=e.target,button=form.querySelector('[type="submit"]');button.disabled=true;try{const b=Object.fromEntries(new FormData(form));await api('drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});if(route==='studio')await renderDrafts(document.querySelector('#personal-body'));toast('草稿已保存');}catch(error){form.querySelector('#draft-status').textContent=error.message;}finally{button.disabled=false;}});



let videoUploadBusy=false;
const videoState={reserved:'等待上传',uploading:'上传处理中',failed:'上传未完成',ready:'视频已保存 · 未发布',review:'已提交审核 · 尚未公开',approved:'审核通过 · 等待上架功能接入'};
async function renderDrafts(body){
 const data=await api('videos');if(route!=='studio')return;
 body.innerHTML=`<section class="upload-panel"><h2>上传动态壁纸</h2><p>选择 MP4 视频，上传后预览并填写作品信息。</p><label class="pill video-pick">选择 MP4 视频<input type="file" accept="video/mp4,.mp4" data-new-video aria-label="选择 MP4 视频" ${videoUploadBusy?'disabled':''}></label><p class="subtitle">单个视频最多 25 MB · 账号已用 ${(data.used/1024/1024).toFixed(1)} / 250 MB</p><progress id="video-progress" value="0" max="100" hidden></progress><p id="video-upload-status" role="status"></p></section><h2 class="draft-heading">我的视频壁纸</h2><section class="video-library">${data.items.map(v=>`<article class="video-work" data-video-card="${v.id}">${['ready','review','approved'].includes(v.state)?`<video controls loop playsinline preload="none" ${v.poster?`poster="${escape(v.poster)}"`:''} src="/api/videos/${v.id}/content" aria-label="${escape(v.title)} 视频预览"></video>`:`<div class="empty">${videoState[v.state]||'处理中'}</div>`}<form data-video-form="${v.id}" method="post"><label>作品标题<input name="title" maxlength="100" required value="${escape(v.title)}" ${['review','approved'].includes(v.state)?'disabled':''}></label><label>作品简介<textarea name="description" maxlength="1500" rows="3" ${['review','approved'].includes(v.state)?'disabled':''}>${escape(v.description)}</textarea></label><p class="subtitle">${videoState[v.state]||v.state} · ${(v.size/1024/1024).toFixed(1)} MB</p><div class="detail-actions">${!['review','approved'].includes(v.state)?'<button class="pill secondary" type="submit">保存信息</button>':''}${v.state==='ready'?`<button class="pill" type="button" data-submit-video="${v.id}">提交发布审核</button>`:''}${['failed','reserved','uploading'].includes(v.state)?`<label class="pill secondary video-pick">重新选择原视频重试<input type="file" accept="video/mp4,.mp4" data-retry-video="${v.id}" aria-label="重新选择 ${escape(v.title)}"></label>`:''}<button class="text-button" type="button" data-remove-video="${v.id}">移除视频</button></div><p class="video-feedback" role="status">${v.state==='ready'&&v.review_reason?'退回原因：'+escape(v.review_reason):''}</p></form></article>`).join('')||'<div class="empty">还没有视频壁纸，先上传一段你创作的动态视频。</div>'}</section><details class="legacy-drafts"><summary>之前保存的文字草稿</summary><div id="legacy-drafts-body"></div></details>`;
 growBio();body.querySelector('.legacy-drafts').addEventListener('toggle',async e=>{if(e.target.open&&!body.querySelector('#legacy-drafts-body').textContent)try{await renderTextDrafts(body.querySelector('#legacy-drafts-body'));}catch(error){body.querySelector('#legacy-drafts-body').textContent=error.message;}});
}
async function videoPreview(file){
 const url=URL.createObjectURL(file),video=document.createElement('video');video.muted=true;video.preload='auto';video.playsInline=true;
 try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('视频读取超时，请换一个 MP4 文件。')),20000);video.onloadeddata=()=>{clearTimeout(timer);resolve();};video.onerror=()=>{clearTimeout(timer);reject(Error('浏览器无法播放这个视频，建议导出 H.264 编码的 MP4。'));};video.src=url;});
 if(!Number.isFinite(video.duration)||video.duration<=0||!video.videoWidth||!video.videoHeight)throw Error('无法识别视频时长或尺寸。');
 const canvas=document.createElement('canvas');canvas.width=400;canvas.height=Math.max(1,Math.round(400*video.videoHeight/video.videoWidth));if(canvas.height>800){canvas.height=800;canvas.width=Math.round(800*video.videoWidth/video.videoHeight);}canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);let poster=canvas.toDataURL('image/jpeg',0.65);if(poster.length>60000)poster=canvas.toDataURL('image/jpeg',0.35);return poster.length<=60000?poster:'';
 }finally{video.removeAttribute('src');video.load();URL.revokeObjectURL(url);}
}
function uploadVideoBytes(id,file,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT','/api/videos/'+id+'/content');xhr.setRequestHeader('Content-Type','video/mp4');xhr.timeout=10*60000;xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.round(e.loaded/e.total*100));};xhr.onerror=()=>reject(Error('网络中断，请重新选择原视频重试。'));xhr.ontimeout=()=>reject(Error('上传超时，请稍后重试。'));xhr.onload=()=>{let data;try{data=JSON.parse(xhr.responseText)}catch{reject(Error('服务器未正确响应，请重试。'));return;}if(xhr.status>=200&&xhr.status<300)resolve(data);else reject(Error(data.error||'上传失败，请重试。'));};xhr.send(file);});}
async function startVideoUpload(input){if(videoUploadBusy||!input.files.length)return;videoUploadBusy=true;input.disabled=true;const status=document.querySelector('#video-upload-status'),progress=document.querySelector('#video-progress');let id=input.dataset.retryVideo;
 try{const file=input.files[0];if(!/\.mp4$/i.test(file.name)||file.size>25*1024*1024||file.size<32)throw Error('请选择 25 MB 以内的 MP4。');status.textContent='正在读取视频并生成封面…';const poster=await videoPreview(file);
 if(!id){const sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('');const record=await api('videos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:file.name.replace(/\.mp4$/i,'').slice(0,100),size:file.size,sha256,poster})});id=record.id;}
 progress.hidden=false;progress.value=0;status.textContent='正在上传…';await uploadVideoBytes(id,file,percent=>{progress.value=percent;status.textContent=percent===100?'正在校验并保存视频…':`正在上传 ${percent}%`;});status.textContent='视频已保存到云端。';toast('视频上传成功');if(route==='studio')await renderDrafts(document.querySelector('#personal-body'));
 }catch(error){status.textContent=error.message+(id?' 可以重新选择原视频重试。':'');if(id)input.dataset.retryVideo=id;toast(error.message);}finally{videoUploadBusy=false;input.disabled=false;input.value='';const pick=document.querySelector('[data-new-video]');if(pick)pick.disabled=false;}
}
document.addEventListener('change',e=>{if(e.target.matches('[data-new-video],[data-retry-video]'))startVideoUpload(e.target);});
async function saveVideoInfo(form){return api('videos/'+form.dataset.videoForm,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});}
document.addEventListener('submit',async e=>{if(!e.target.matches('[data-video-form]'))return;e.preventDefault();const form=e.target,button=form.querySelector('[type=submit]');button.disabled=true;try{await saveVideoInfo(form);form.querySelector('.video-feedback').textContent='作品信息已保存。';}catch(error){form.querySelector('.video-feedback').textContent=error.message;}finally{button.disabled=false;}});
document.addEventListener('click',async e=>{const submit=e.target.closest('[data-submit-video]'),remove=e.target.closest('[data-remove-video]');if(!submit&&!remove)return;const button=submit||remove,form=button.closest('form');if(remove&&!confirm('移除这段云端视频？文件将被删除，已提交的审核也会撤回。'))return;button.disabled=true;try{if(submit){await saveVideoInfo(form);await api('videos/'+submit.dataset.submitVideo+'/submit',{method:'POST'});toast('已提交审核，尚未公开发布');}else await api('videos/'+remove.dataset.removeVideo,{method:'DELETE'});if(route==='studio')await renderDrafts(document.querySelector('#personal-body'));}catch(error){form.querySelector('.video-feedback').textContent=error.message;}finally{button.disabled=false;}});

async function renderModeration(){
 app.innerHTML='<section class="intro-line"><h1>作品审核</h1></section><div id="review-body">正在读取…</div>';
 try{const data=await api('moderation');if(route!=='moderation')return;
 document.querySelector('#review-body').innerHTML='<p class="subtitle">查看所有创作者提交的壁纸。通过后保留审核结果；公开上架功能正在接入。</p><section class="video-library">'+(data.items.map(v=>`<article class="video-work"><video controls preload="none" playsinline poster="${escape(v.poster)}" src="/api/moderation/${v.id}/content"></video><h2>${escape(v.title)}</h2><a href="#people/${escape(v.login)}">@${escape(v.login)}</a><p>${escape(v.description)}</p><p>${escape(videoState[v.state]||v.state)}</p>${v.state==='review'?`<form data-review-form="${v.id}"><label>审核说明<textarea name="reason" maxlength="500" rows="2" placeholder="退回时请告诉作者需要修改什么"></textarea></label><div class="detail-actions"><button class="pill" type="submit" value="approve">通过审核</button><button class="pill secondary" type="submit" value="reject">退回修改</button></div><p role="status"></p></form>`:`<p>${escape(v.reason||'审核已完成')}</p>`}</article>`).join('')||'<div class="empty">暂时没有待审核的作品。</div>')+'</section>';
 }catch(e){if(route==='moderation')document.querySelector('#review-body').textContent=e.message;}
}
document.addEventListener('submit',async e=>{if(!e.target.matches('[data-review-form]'))return;e.preventDefault();const form=e.target,decision=e.submitter?.value,reason=form.elements.reason.value.trim();if(decision==='reject'&&!reason){form.querySelector('[role=status]').textContent='请填写退回原因。';return;}form.querySelectorAll('button').forEach(x=>x.disabled=true);try{await api('moderation/'+form.dataset.reviewForm,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,reason})});toast(decision==='approve'?'已通过审核':'已退回，作者可查看原因');await renderModeration();}catch(error){form.querySelector('[role=status]').textContent=error.message;}finally{form.querySelectorAll('button').forEach(x=>x.disabled=false);}});
