package net.ccbcm.wallpaper;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.widget.*;
import java.io.*;import java.net.*;import java.security.*;import java.util.concurrent.*;import org.json.*;
public class MainActivity extends Activity {
 TextView status; final ExecutorService jobs=Executors.newSingleThreadExecutor(); boolean busy=false;
 void message(String text){runOnUiThread(()->{if(!isFinishing())status.setText(text);});}
 void link(){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://ccbcm.net/#downloads")));}
 @Override public void onCreate(Bundle state){super.onCreate(state);LinearLayout layout=new LinearLayout(this);layout.setOrientation(LinearLayout.VERTICAL);layout.setPadding(48,100,48,48);layout.setBackgroundColor(0xff191820);TextView title=new TextView(this);title.setText("CCBCM 壁纸");title.setTextSize(27);title.setTextColor(0xffeee9f5);layout.addView(title);status=new TextView(this);status.setText("从网站的「我的下载」选择壁纸。\n预览版：播放能力取决于手机解码支持。");status.setTextSize(16);status.setTextColor(0xffc9c3d3);status.setPadding(0,35,0,35);layout.addView(status);Button button=new Button(this);button.setText("打开我的下载");GradientDrawable bg=new GradientDrawable();bg.setColor(0xffd3c2f7);bg.setCornerRadius(60);button.setBackground(bg);button.setTextColor(0xff252031);button.setOnClickListener(v->link());layout.addView(button);setContentView(layout);accept(getIntent());}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);accept(intent);}
 void accept(Intent intent){Uri uri=intent.getData();if(uri==null||busy)return;String id=uri.getLastPathSegment();if(!"ccbcm-mobile".equals(uri.getScheme())||!"apply".equals(uri.getHost())||id==null||!id.matches("[a-f0-9]{64}|blue|cat|lines|caffeine|tux")){message("壁纸链接无效，请从网站重新选择。");return;}busy=true;message("正在准备壁纸，请稍候…");jobs.execute(()->{try{JSONObject info=new JSONObject(new String(fetch("https://ccbcm.net/api/published-videos/"+id+"/manifest",4096),"UTF-8"));String mime=info.optString("mime",id.equals("blue")?"video/mp4":"image/png"),sha=info.getString("sha256");long size=info.getLong("size");if(size<32||size>200L*1024*1024||!sha.matches("[a-f0-9]{64}")||!mime.matches("video/(mp4|webm|quicktime|x-matroska)|image/(png|jpeg)"))throw new IOException("壁纸格式无效");File file=new File(getFilesDir(),sha+".wallpaper");if(!file.exists()||file.length()!=size||!digest(file).equals(sha)){
 File temp=new File(getFilesDir(),sha+".part");try{String url=id.length()==64?"https://ccbcm.net/api/published-videos/"+id+"/content":"https://ccbcm.net/gallery/media/"+id+(id.equals("blue")?".mp4":".png");HttpURLConnection connection=connect(url);try(InputStream in=connection.getInputStream();OutputStream out=new FileOutputStream(temp)){byte[] b=new byte[65536];int n;long total=0;while((n=in.read(b))!=-1){total+=n;if(total>size)throw new IOException("文件大小不符");out.write(b,0,n);}if(total!=size)throw new IOException("下载未完成");}finally{connection.disconnect();}if(!digest(temp).equals(sha))throw new IOException("文件校验失败");if(!temp.renameTo(file))throw new IOException("无法保存壁纸");}finally{temp.delete();}}
 runOnUiThread(()->{busy=false;if(isFinishing())return;if(mime.startsWith("image/"))chooseImage(file);else chooseVideo(file);});
 }catch(Exception error){busy=false;message("暂时无法使用："+error.getMessage()+"。请重试。");}});}
 static HttpURLConnection connect(String url)throws IOException{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(20000);c.setReadTimeout(30000);if(c.getResponseCode()!=200){c.disconnect();throw new IOException("作品已下架或网络不可用");}return c;}
 static byte[] fetch(String url,int max)throws IOException{HttpURLConnection c=connect(url);try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[1024];int n;while((n=in.read(b))!=-1){if(out.size()+n>max)throw new IOException("响应过大");out.write(b,0,n);}return out.toByteArray();}finally{c.disconnect();}}
 static String digest(File file)throws Exception{MessageDigest sha=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(file)){byte[] b=new byte[65536];int n;while((n=in.read(b))!=-1)sha.update(b,0,n);}StringBuilder text=new StringBuilder();for(byte b:sha.digest())text.append(String.format("%02x",b&255));return text.toString();}
 void chooseVideo(File file){getSharedPreferences("wallpaper",0).edit().putString("path",file.getAbsolutePath()).apply();try{startActivity(new Intent(WallpaperManager.ACTION_CHANGE_LIVE_WALLPAPER).putExtra(WallpaperManager.EXTRA_LIVE_WALLPAPER_COMPONENT,new ComponentName(this,VideoWallpaper.class)));message("请在系统预览中确认。锁屏选项由手机系统提供。");}catch(Exception e){message("这台手机没有开放动态壁纸设置。");}}
 void chooseImage(File file){new AlertDialog.Builder(this).setTitle("用在哪里？").setItems(new String[]{"桌面","锁屏","桌面和锁屏"},(dialog,which)->{message("正在设置…");jobs.execute(()->{try{BitmapFactory.Options opts=new BitmapFactory.Options();opts.inJustDecodeBounds=true;BitmapFactory.decodeFile(file.getAbsolutePath(),opts);opts.inSampleSize=1;while(Math.max(opts.outWidth,opts.outHeight)/opts.inSampleSize>4096)opts.inSampleSize*=2;opts.inJustDecodeBounds=false;Bitmap bitmap=BitmapFactory.decodeFile(file.getAbsolutePath(),opts);if(bitmap==null)throw new IOException("图片无法解码");try{WallpaperManager.getInstance(this).setBitmap(bitmap,null,true,which==0?WallpaperManager.FLAG_SYSTEM:which==1?WallpaperManager.FLAG_LOCK:WallpaperManager.FLAG_SYSTEM|WallpaperManager.FLAG_LOCK);}finally{bitmap.recycle();}message("壁纸已设置。");}catch(Exception e){message("设置失败："+e.getMessage());}});}).show();}
 @Override protected void onDestroy(){jobs.shutdown();super.onDestroy();}
}
